Kingfisher/ImageCache.swift, Kingfisher/ImageDownloader.swift, Kingfisher/KingfisherManager.swift, Kingfisher/UIImageView+Kingfisher.swift, KingfisherTests/ImageDownloaderTests.swift, Pods/Pods.xcodeproj/project.pbxproj, README.md
We'd better take care about case sensitive.
=> Replace all 'url' with 'URL'.

Kingfisher-Demo/ViewController.swift, Kingfisher.podspec, Kingfisher/ImageCache.swift, Kingfisher/ImageDownloader.swift, Kingfisher/KingfisherManager.swift, Kingfisher/KingfisherOptions.swift, Kingfisher/UIButton+Kingfisher.swift, Kingfisher/UIImageView+Kingfisher.swift, KingfisherTests/ImageCacheTests.swift, KingfisherTests/ImageDownloaderTests.swift, KingfisherTests/UIButtonExtensionTests.swift, KingfisherTests/UIImageViewExtensionTests.swift
Since there is API modification. I think it should be 1.3.0 instead of 1.2.1.
---
=> [WIP] 1.3.0

README.md
I've just noticed the logo is kinda blurry on my iMac 5K and found some typos. Meanwhile, the original badge of CircleCI is ugly.
If you prefer a full-width logo anyway, you'd better export a new image with 728pt(1456px) in width.
=> Improve the consistency of badges and fix typos.

Kingfisher/ImageCache.swift
According to logs in #86 , it seems there is a case that Swift failed to convert `AnyObject` to its dynamic type correctly.
I believe this commit fixed it by an explicitly type casting. However. since I cannot reproduce the crash in my development environment, it is just an attempt for it without verification.
=> Try to fix issue 86

Kingfisher/ImageCache.swift, KingfisherTests/ImageCacheTests.swift
stringByAppendingPathComponent seems to have become a NSString exclusive method on Xcode 7 beta 5, this is just a quick fix.
=> fix compile error on xcode 7 beta 5

Kingfisher-Demo/ViewController.swift, Kingfisher.xcodeproj/project.pbxproj, Kingfisher/KingfisherManager.swift, Kingfisher/Resource.swift, Kingfisher/UIButton+Kingfisher.swift, Kingfisher/UIImageView+Kingfisher.swift, KingfisherTests/UIImageViewExtensionTests.swift
This pull-request added resource based API for Kingfisher. We could decouple the target URL and the cache key by using this resource APIs. See #93 for more.
=> Resource based api

Kingfisher-Demo/Base.lproj/Main.storyboard, Kingfisher-Demo/ViewController.swift, Kingfisher.xcodeproj/project.pbxproj, Kingfisher/Info.plist, Kingfisher/KingfisherManager.swift, Kingfisher/KingfisherOptionsInfo.swift, Kingfisher/UIButton+Kingfisher.swift, Kingfisher/UIImageView+Kingfisher.swift, KingfisherTests/ImageCacheTests.swift, KingfisherTests/KingfisherManagerTests.swift, KingfisherTests/UIImageViewExtensionTests.swift, README.md
This p-r fixed the #123, by introducing a type-safe way to use `KingfisherOptionsInfo`.
It will break current code if you are using options. But it is fairly easy to fix it. Just change your original code
```swift
let optionsInfos: KingfisherOptionsInfo = 
[
.Options: [KingfisherOptions.CacheMemoryOnly, KingfisherOptions.ForceRefresh], 
.Transition: ImageTransition.Fade(1)
]
```
to something like this:
```swift
let optionsInfos: KingfisherOptionsInfo = 
[
.Options([KingfisherOptions.CacheMemoryOnly, KingfisherOptions.ForceRefresh]), 
.Transition(ImageTransition.Fade(1))
]
```
=> Fix options types

Kingfisher/ImageCache.swift, Kingfisher/Info.plist
There is a retain cycle because we are capturing self strongly within a closure, this is causing the memory to not released. This can easily be fixed by capturing the self as weak.
=> Fix a retain cycle

Kingfisher/ImageCache.swift, KingfisherTests/ImageCacheTests.swift
Added an optional path parameter to init. This is really useful for me as I want a cache in documents dir for user generated photos, and also to make the ImageCache backwards compatible from an existing cache.
=> ImageCache - custom cache path

README.md
println() has been renamed print() in Swift 2.0
=> Replace println() with print()

Kingfisher/UIImage+Extension.swift
If a GIF image has been decoded, it will lose it's images, become a static image.
请作者看看是否有必要对 images 内的图像再做 decode？
=> Do not decode an animated image.

README.md
Should improve the :us: 
Library looks :+1:
=> Some minor Englishification on the README

Kingfisher/ImageCache.swift
This is a followup pull request on #202.
If originalData is available it will be used in favour of the supplied image to store to the cache.
This will omit compressing the image in case of a JPEG.
=> use originalData in favour of image

Sources/ImageCache.swift, Sources/ImageDownloader.swift, Sources/ImageView+Kingfisher.swift, Sources/ThreadHelper.swift, Sources/UIButton+Kingfisher.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift, Tests/KingfisherTests/KingfisherManagerTests.swift
@dopcn
在你的基础上改动了一些：
1. `ImageView` 和 `UIButton` 的 extension 中因为涉及的是 UI 操作，所以必须是 main thread；
2. `ImageCache` 里从内存缓存中直接取的时候并不需要进行 dispatch，否则将造成刷新时的闪烁；
3. 因此调整了一下 ThreadHelper 中的内容，依然还是进行一下判定，如果已经在 main queue 的话就不再做 dispatch 了；
因为从磁盘缓存读取为了性能考虑需要放在另外的线程执行，所以在内存无缓存但磁盘有缓存时刷新的闪烁似乎是不可避免的，不过因为这种情况并不是很常见或者致命。现在并不想添加像是在主线程读取磁盘缓存的选项，所以决定暂时先维持现状这样。稍后会在 `optionsInfo` 中添加一个强制进行 transition 的标识，如果用户觉得磁盘缓存读取的闪烁不可接受的话可以用像是 fade 之类的过度来缓解。
如果没有什么其它问题的话可以应该 merge 了。
=> Apply callback queue to downloader as well

Sources/ImageCache.swift, Sources/ImageDownloader.swift, Sources/ImageView+Kingfisher.swift, Sources/UIButton+Kingfisher.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift, Tests/KingfisherTests/KingfisherManagerTests.swift
实现的效果仍然是当不显式指定 callbackQueue 时 completionHandler 在 main queue 上调用，显示指定 callbackQueue 则在指定 queue 上运行，无论何时 progressBlock 都在 main queue 上调用
原本在 ImageDownloader 里 session object 的 delegateQueue 是 main queue，所以可能是这个原因导致了会出现在 main queue 调用 `dispatch_async(dispatch_get_main_queue(), ...) `  的情况，例如最终调用 completionHandler 的是函数
`private func callbackWithImage(image: Image?, error: NSError?, imageURL: NSURL, originalData: NSData?) {}`
这个函数在原本的实现中有可能在 processQueue 上被调用
（函数 `processImageForTask` 的实现），
也有可能在 main queue 上被调用
（`URLSession(session: NSURLSession, task: NSURLSessionTask, didCompleteWithError error: NSError?)` 的实现）
在 main queue 上被调用，在 handler 里又包含 `dispatch_async(dispatch_get_main_queue(), ...) ` 就会导致 reload 时出现闪动。
新的实现将 session object 的 delegateQueue 改为自定义的 operation queue 所有的 delegate …
=> move queue dispatch code into ImageDownloader

Sources/ThreadHelper.swift
Thanks for this resource! 
Changed "methd" to "method" in ThreadHelper.swift
=> fixed typo in documentation

Sources/ImageView+Kingfisher.swift
When using Kingfisher with any type of animation, it was just breaking user interaction and not allowing users to scroll through lists on interact with the `UIImageView`s themselves.
This was mostly due to the fact that `.AllowUserInteraction` was not an option on the `UIView.transitionWithView` call.
=> Added user interaction to animation

Sources/ImageCache.swift
Understandably, the method was private; however, this commit solves the problem of anyone that requires access to the actual file path of the cached image. This is especially useful for projects that are building iOS apps that are showing content with `UIWebView`s and lacks access to Internet connection.
Ref: #255
=> Make cachePathForKey public [resolves #255]

Sources/ImageCache.swift, Tests/KingfisherTests/ImageCacheTests.swift
- this improves the performance of image loading for in-memory cached
images.
We observe a flicker when returing to an image view that renders
multiple images using `kf_setImageWithResource`.  We traced through the
calls and found a place where Kingfisher attempts to re-decode an image
that has already been decoded and stored in the in memory cache.
We think that it is safe to pull out an image from the in memory cache and not
attempt to decode again.
=> Disable background decoding for images from the in memory cache.

Sources/Image.swift
Allow images with other formats than JPEG, PNG or GIF to be converted from downloaded image data (.ICO, as example)
=> Allow images other than JPEG, PNG or GIF (.ICO, as example)

Sources/String+MD5.swift
This p-r fixes an issue in Swift Generator. This is reported here: https://github.com/onevcat/Kingfisher/issues/280
After some research, I found when using a closure based generator, a leak will happen in Release build in `_GeneratorBox.__allocating_init(A) -> _GeneratorBox`. It does not relate to Kingfisher's code, since there are [some minimal examples](https://gist.github.com/onevcat/3da91b1b1c9409c9e57536a5736396f0) are also reported to be leaking by Instruments.
Turn to a normal `GeneratorType` instead of closure based one could solve this problem.
=> Workaround a closure based generator leak in Swift

Sources/ImageView+Kingfisher.swift, Sources/UIButton+Kingfisher.swift
Since Xcode autocompletion improves for Swift 2.2.
=> Remove duplicated APIs

Kingfisher.xcodeproj/project.pbxproj, NSButton+Kingfisher.swift, Tests/KingfisherTests/NSButtonExtensionTests.swift
I am not sure if there's a way to combine UIButton with NSButton. So I didn't change UIButton+extension, for now, I just create a new file to implement NSButton as it doesn't have backgroundImage property but alternateImage instead.
=> implement NSButton extension for OSX

Sources/ImageCache.swift
Inspired by [SDWebImage](https://github.com/rs/SDWebImage/issues/1082), using runtime to judge      whether sharedApplication() is available in current target #269 .
It also can be done with the compile flags
=> Add support for App Extension target

Sources/ImageCache.swift
Was interested in how ImageCache worked, and started poking around the source. Noticed two instances where code could be simplified by using default arguments. I'm not sure if this was intentionally left this way, but it appears to me that there is no compelling reason to have two separate method signatures for these aspects of ImageCache. Let me know either way!
=> Simplify some code using default arguments

Kingfisher.xcodeproj/project.pbxproj, README.md, Sources/AnimatedImageView.swift, Sources/Image.swift, Sources/ImageCache.swift, Sources/ImageDownloader.swift, Sources/ImageView+Kingfisher.swift, Sources/KingfisherOptionsInfo.swift, Tests/KingfisherTests/ImageExtensionTests.swift
* Improve memory usage for GIF images by avoiding preload all the data once.
* Introduce `AnimatedImageView` to play progressing loading GIF data.
* Keep back compatibility for earlier versions, so you can still play GIF in regular `UIImageView` with the old way.
=> GIF performance

Sources/AnimatedImageView.swift
This problem occured when you are using `replace segue` to show the view controller which have Kingfisher.AnimatedImageView kind property.
=> Fix 'Cannot form weak reference to instance of class Kingfisher.AnimatedImageView'

Sources/ImageCache.swift
Fix a crash when switching app to background and foreground multiple times, due to an over-releasing of application object.
=> Application object Unretained Value

Sources/AnimatedImageView.swift
I replaced `type` with `value`. Thank you for pointing it out.
This PR is related to https://github.com/onevcat/Kingfisher/pull/312.
=> Avoid variable name min length rule violation by SwiftLint

Sources/ImageDownloader.swift, Sources/KingfisherManager.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift
Fix some cases where "download" is misspelled. This should not be a breaking change, because all names modified are non-public.
=> Fix spelling

Sources/ImageCache.swift, Tests/KingfisherTests/ImageCacheTests.swift
First of all thank you for your fantastic Library!
We notified some crashes in production cause by the fact that the cache type was implicitly unwrapped and if was `nil` if the image is not cached
=> Removed Implicit Unwrapping of CacheType

Sources/ImageDownloader.swift, Tests/KingfisherTests/ImageDownloaderTests.swift
I'm sorry for the previous one.
This is mentioned at #245
Currently, when server respond with 404 and image content type, this will cache the image and not give us any information.
I think it's not good. 
This change will make kingfisher to avoid to cache image when server respond with invalid status code like 404.
When status code is not 200 or 201, callback handler include error which has status code and localized description.
Thank you for your great library.
=> Cancel donwloading when status code is invalid

Kingfisher.xcodeproj/project.pbxproj, Sources/ImageDownloader.swift
Use Legacy Swift Language Version -> No
fixed build errors for Demo app.
=> fix build errors on Xcode 8 beta 4 for Demo

Sources/Image.swift, Tests/KingfisherTests/ImageCacheTests.swift
Fix gif frame duration calculation to match that of webkit
This bug caused wrong animation speeds for some gif when not using AnimateImage
=> Fix gif frame duration calculation to match that of webkit

.travis.yml
According to https://github.com/travis-ci/travis-ci/issues/2168, xcpretty is now preinstalled on macOS VMs.
=> Remove gem install xcpretty

Sources/ImagePrefetcher.swift
requestedCount incremented beyond the prefetchedResorces count. See Issue #316  
Fix: eliminate requestedCount
Because the start() method captures the initial X Resources by index and ships them off to startPrefetchingResource() and that methods recursive behavior, you can end up in a state where all the items have been processed but the initial X resources will get double processed because they were captured in the for loop in the start() method and again in the recursion of the startPrefetchingResource(). So if during the prefetch you get into this state and you call stop() you will end up with an unbalanced Range when sorting out the failedResources.
=> Fix for Issue 316. Crash: 'Fatal Error: Can't form Range with end < start

Demo/Kingfisher-Demo/ViewController.swift, Demo/Kingfisher-macOS-Demo/ViewController.swift, Kingfisher.swift, Kingfisher.xcodeproj/project.pbxproj, Sources/AnimatedImageView.swift, Sources/CacheSerializer.swift, Sources/Filter.swift, Sources/Image.swift, Sources/ImageCache.swift, Sources/ImageDownloader.swift, Sources/ImagePrefetcher.swift, Sources/ImageProcessor.swift, Sources/ImageView+Kingfisher.swift, Sources/Indicator.swift, Sources/KingfisherOptionsInfo.swift, Sources/NSButton+Kingfisher.swift, Sources/String+MD5.swift, Sources/UIButton+Kingfisher.swift, Tests/KingfisherTests/ImageExtensionTests.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift, Tests/KingfisherTests/KingfisherTestHelper.swift, Tests/KingfisherTests/NSButtonExtensionTests.swift, Tests/KingfisherTests/StringExtensionTests.swift, Tests/KingfisherTests/UIButtonExtensionTests.swift
Change the way of implement namespacing extension #435
=> Another way of adding kf namespacing

Demo/Kingfisher-Demo/ViewController.swift, Demo/Kingfisher-macOS-Demo/ViewController.swift, Kingfisher.swift, Kingfisher.xcodeproj/project.pbxproj, Sources/AnimatedImageView.swift, Sources/CacheSerializer.swift, Sources/Filter.swift, Sources/Image.swift, Sources/ImageCache.swift, Sources/ImageDownloader.swift, Sources/ImagePrefetcher.swift, Sources/ImageProcessor.swift, Sources/ImageView+Kingfisher.swift, Sources/Indicator.swift, Sources/KingfisherOptionsInfo.swift, Sources/NSButton+Kingfisher.swift, Sources/String+MD5.swift, Sources/UIButton+Kingfisher.swift, Tests/KingfisherTests/ImageExtensionTests.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift, Tests/KingfisherTests/KingfisherTestHelper.swift, Tests/KingfisherTests/NSButtonExtensionTests.swift, Tests/KingfisherTests/StringExtensionTests.swift, Tests/KingfisherTests/UIButtonExtensionTests.swift
This p-r adopts to a new namespacing system. It could avoid possible naming conflicting by introducing an extra struct layer. So we could get rid of the `kf_` prefix. Instead, we could use an easier `kf.` to limit Kingfisher related APIs in its own namespace.
=> Add kf namespacing

Sources/ImageCache.swift, Tests/KingfisherTests/ImageCacheTests.swift
Especially useful when using Kingfisher on macOS and wanting to add
drag-drop. Most web input fields won't accept files without a path
extension (like .jpg).
Currently only supports a single default path extension. Could later
be expanded to include a path extension per image.
=> Add option to supply default path extension

Sources/Image.swift
Might be related to #459 and #440
=> CGImage fix seems not necessary

Sources/String+MD5.swift
I profiled Kingfisher’s compile time after reading this:
http://irace.me/swift-profiling
With this small change, I was able to speed up compile time dramatically.
Before:
```
2517.2ms  Kingfisher/Sources/String+MD5.swift:213:10  func calculate() -> [UInt8]
2444.7ms  Kingfisher/Sources/String+MD5.swift:282:20  (closure)
2320.0ms  Kingfisher/Sources/String+MD5.swift:213:10  func calculate() -> [UInt8]
2251.4ms  Kingfisher/Sources/String+MD5.swift:282:20  (closure)
113.8ms Kingfisher/Sources/String+MD5.swift:129:6 func toUInt32Array(_ slice: ArraySlice<UInt8>) -> Array<UInt32>
108.5ms Kingfisher/Sources/String+MD5.swift:129:6 func toUInt32Array(_ slice: ArraySlice<UInt8>) -> Array<UInt32>
47.5ms  Kingfisher/Sources/String+MD5.swift:63:6  func arrayOfBytes<T>(_ value: T, length: Int? = …
```
=> Reduce Swift compile time.

Sources/ImageCache.swift
Put `open` functions in extensions into class definition to be able to override `open` functions in subclasses. Before if you tried to do it you'd gotten the Swift error: `Declarations from extensions cannot be overridden yet`.
=> Put `open` functions in extensions into class definition

Sources/ImageView+Kingfisher.swift, Sources/KingfisherOptionsInfo.swift, Sources/NSButton+Kingfisher.swift, Sources/UIButton+Kingfisher.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift, Tests/KingfisherTests/KingfisherOptionsInfoTests.swift
This is an implementation for #494
=> Add an option to keep current image while loading

Sources/ImageDownloader.swift, Tests/KingfisherTests/ImageDownloaderTests.swift
Since we do not support Objective-C now, it would be a good idea to remove `NSObject` superclass from `ImageDownloader`. This could also be a workaround for #520
=> Make ImageDownloader non-objc

Sources/AnimatedImageView.swift, Sources/ImageView+Kingfisher.swift
Prepare and preload animated frames asynchronously can improve performance apparently.
While there are more than 25 visible GIFs on screen, FPS is raised from 30 to ≈60.
=> Fix preload animated image and improve performance

Sources/Image.swift
Attempting to access either `kf.gifRepresentation()` or `kf.animatedImageData` in my project was throwing an `inaccessible due to 'internal' protection level` error. Explicitly making those methods public fixes the issue.
=> Make Image representation methods public

.travis.yml, Sources/ImageCache.swift, Tests/KingfisherTests/ImageCacheTests.swift
=> Support unlimited disk cache time

Sources/ImageDownloader.swift, Sources/ImageView+Kingfisher.swift, Sources/KingfisherManager.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift
Remove cancelable disk task. Change the download task behavior to make it could be cancelled even before the task starts.
Fix for #532
=> Modify disk and download task cancel logic

Sources/ImageView+Kingfisher.swift, Sources/NSButton+Kingfisher.swift, Sources/UIButton+Kingfisher.swift
For the case 'setImage twice for different url, and progressBlock will cross, like A1%, A50%, B20%, A100%, B60% ...'.
=> Ignore progressBlock if imageUrl is not equal to current imageUrl.

Demo/Kingfisher-macOS-Demo/ViewController.swift, Sources/CacheSerializer.swift, Sources/Image.swift, Sources/ImageProcessor.swift, Sources/KingfisherOptionsInfo.swift, Tests/KingfisherTests/ImageExtensionTests.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift, Tests/KingfisherTests/KingfisherOptionsInfoTests.swift
This pull-request implements the feature of only loading the first frame of a GIF file.
It could help to save memory when loading a list (table view) of GIF file. Originally, all the GIFs will be loaded and animated. However, it is not a good idea to do so, since it will eat quite a lot of memory. Instead, we may want to load and decode the first frame of a GIF file as a preview or thumbnail. Then user could be navigated to a detail view will full, animating GIF image.
=> Feature gif first image

Sources/AnimatedImageView.swift, Sources/Image.swift
=> Use default duration if no valid gif frame info

Sources/ImageView+Kingfisher.swift
Hi,
while using Kingfisher in a collection view I noticed that in some cases the image views weren't updated as expected.
This is what I'm doing:
- Dequeue a reusable cell containing an image view
- Set the image to a certain `image-url` using KF
- At some point the cell gets reused and the download KF download canceled
- Set the image to `nil` with a placeholder
What I expect at this point is for the image view to display the placeholder, what happens is that it still displays the image at `image-url`.
I looked a bit into the `setImage` method in `ImageView+Kingfisher` and noticed that the cause of this issue might be the fact that `webURL` is not updated when setImage is called with a `nil` resource thus letting the completion block of the download task update the image even if the …
=> Also set the webURL to nil when resource is nil

Sources/ImageProcessor.swift
Default behavior doesn't change, using ContentMode.none as a default value
=> Allow ResizingImageProcessor to resize image using size proxy aspectFit & aspectFill

Sources/ImageCache.swift
- Fix https://github.com/onevcat/Kingfisher/issues/619
=> Use other method to enumerate contents, which causing crash(maybe only occurred for archved build)

Sources/Image.swift
when both set backgroundDecode and scaleFactor, the size is wrong and the final image is wrong too
=> fix wrong size

Sources/Image.swift
The `colorSpace` variable in `Image.decoded` was assigned but never used.
=> Remove unused colorSpace

Kingfisher.xcodeproj/xcshareddata/xcschemes/Kingfisher-macOS.xcscheme, Kingfisher.xcodeproj/xcshareddata/xcschemes/Kingfisher-tvOS.xcscheme, Kingfisher.xcodeproj/xcshareddata/xcschemes/Kingfisher.xcscheme
As discussed in #752, disable "Gather coverage data" in the test action of all schemes in order to resolve issues with Kingfisher being used in Xcode 9 apps when using Carthage to compile the framework.
=> Disable gather coverage data in scheme test action

Sources/Image.swift, Sources/ImageProcessor.swift
It allows to specify a background color for the rounded output image.
According to the issue: https://github.com/onevcat/Kingfisher/issues/757
=> Introduced a 'backgroundColor' property on the RoundCornerImageProcessor

Kingfisher.xcodeproj/xcshareddata/xcschemes/Kingfisher-macOS.xcscheme, Kingfisher.xcodeproj/xcshareddata/xcschemes/Kingfisher-tvOS.xcscheme, Kingfisher.xcodeproj/xcshareddata/xcschemes/Kingfisher.xcscheme
iTunes Connect no longer accepts builds with codeCoverageEnabled option turned on, returning this error (in email):
> Invalid Bundle - Disallowed LLVM instrumentation. Do not submit apps with LLVM profiling instrumentation or coverage collection enabled. Turn off LLVM profiling or code coverage, rebuild your app and resubmit the app.
>
>Once these issues have been corrected, you can then redeliver the corrected binary.
This Pull Request turns off codeCoverageEnabled for all schemes.
=> Turn off codeCoverageEnabled for all schemes

Sources/ImageDownloader.swift
This adds possibility to further manipulate downloaded raw image data. Can be used i.e. for decrypting images.
=> Implemented data download callback

Sources/KingfisherManager.swift, Sources/KingfisherOptionsInfo.swift, Tests/KingfisherTests/KingfisherManagerTests.swift
Hey hey 👋,
Here at Zeplin, we needed a way to cache the original images on a different cache (rather than the target cache) when using a custom image processor. For example, we are fetching images with a custom thumbnail image processor, and we want to store these thumbnails on a 'thumbnail' cache, and store the originals on a 'snapshots' cache. 
To accomplish this, we wrote a `originalCache` to `KingfisherOptionsInfoItem` on our fork. `originalCache` is basically used for storing and retrieving original images if paired with a non-default image processor. It defaults to `targetCache` to make it an optional item.
I've also included a typo fix and an optimization to prevent double caching if `cacheOriginalImage` is selected when used with the default image processor.
Thought this may be a …
=> Support caching original images on a different cache

Sources/CacheSerializer.swift
No need to encode images again when original data provided.
=> No need to encode images again

Kingfisher.xcodeproj/project.pbxproj, Sources/ImageModifier.swift, Sources/ImageProcessor.swift, Sources/KingfisherOptionsInfo.swift, Tests/KingfisherTests/ImageModifierTests.swift
Resolves #810
This adds an ImageModifier, allowing edits to be performed on a concrete type of `Image` (ex. UIImage) right before the image is used/displayed.
I've created the `KingfisherOptionsInfoItem` case and `ImageModifier` struct, but the actual modifier isn't being run yet. I'd like advice on where exactly to run the modifier. I think it should go in `downloadAndCacheImage` and `tryToRetrieveImageFromCache`, but I'm not sure; there might be a better place for it.
TODO:
=> [WIP] add ImageModifier

Kingfisher.xcodeproj/project.pbxproj, Sources/Image.swift, Sources/ImageProcessor.swift, Tests/KingfisherTests/ImageProcessorTests.swift
Adds blending/compositing(macOS) processors. Allows easily blend/compositing.
For example, I was needed to blend unedited images which have the different background color so they will appear blended with the background color of my interface.
=> new image processors: blend, compositing

Sources/AnimatedImageView.swift
- Array extension in `AnimatedImageView.swift` uses default access level for `subscript(safe:)` method
- This is a common Array extension method to make, and using this current access control level can lead to `Invalid Redeclaration of function` errors in Xcode
Steps to reproduce:
1) Create a new, empty Swift project, and import the Kingfisher library
2) Add the same Array extension in `AppDelegate.swift`
- Note: this error will occur regardless of the access control level of any duplicate extension (so even a `fileprivate subscript(safe:)` elsewhere will trigger the error)
=> Fix possible invalid redeclaration error

Demo/Kingfisher-watchOS-Demo Extension/InterfaceController.swift, Sources/ImageCache.swift, Sources/ImageDownloader.swift, Sources/ImagePrefetcher.swift, Sources/KingfisherManager.swift, Tests/KingfisherTests/ImageCacheTests.swift, Tests/KingfisherTests/ImageDownloaderTests.swift, Tests/KingfisherTests/ImagePrefetcherTests.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift, Tests/KingfisherTests/NSButtonExtensionTests.swift, Tests/KingfisherTests/UIButtonExtensionTests.swift
闭包返回值Void要比()更精确，表明这是Void类型。而()一般作为空的表达式，也可以作为Void类型。感觉Void更精准
=> make closure return type  -> () modify to -> Void. Void is more accurate than () in return.

Sources/ImageCache.swift
Use Case:
New Images for new Data Models are downloaded in the background but the UI isn't refreshed yet.
So we want to keep the currently visible Images in memory cache so that e.g. a TableViewCell can still display them (from memory cache) but want to delete images from disk cache to keep the disk footprint low.
=> Add option to remove image only from disk cache and not memory

Sources/AnimatedImageView.swift
Fixes #860
Fixes two issues that occur when the image buffer holds less frames than exist in an animated image:
1. Incrementing the loop count would occur when the number of frames in the buffer were displayed, not when all frames in the animated image were displayed.
1. The first loop of the animated image would skip a frame.
1. See the example project linked from #860. You can either open that project and change the Podfile to use `pod 'Kingfisher', :git => 'git@github.com:mliberatore/Kingfisher.git', :branch => 'fix-loop-counting'`, and run `pod install`, or you can download the already updated project here:
[KingfisherLooping.zip](https://github.com/onevcat/Kingfisher/files/1720525/KingfisherLooping.zip).
1. Run the updated project, tap the play button, and see that the gif stops …
=> Fixes Gif Loop Counting and Frame Skipping

Kingfisher-Demo.xcodeproj/project.pbxproj, Kingfisher-Demo.xcodeproj/project.xcworkspace/contents.xcworkspacedata, Kingfisher.xcodeproj/project.pbxproj
How I did this:
- I duplicated the `Kingfisher.xcodeproj`
- Renamed the copy to `Kingfisher-Demo.xcodeproj`
- Deleted the demo files and targets from `Kingfisher.xcodeproj`
- Deleted the framework sources and targets from `Kingfisher-Demo.xcodeproj`
- Added the `Kingfisher.xcodeproj` as a child project to `Kingfisher-Demo.xcodeproj`
- Configured the demo app to use the framework targets built by the child project
- Hid the framework target schemes that are automatically added by the child project so people are not confused to see framework schemes in the demo project
- And I tested building and running all the demo apps successfully.
Phew—I hope I didn’t break anything. 😉
=> Separate demo apps into their own Xcode project.

Kingfisher.podspec
* Specifies the swift version that will be used for the pod regardless of the swift version the app target uses.
Note: This feature was added on CocoaPods 1.4.0 (http://blog.cocoapods.org/CocoaPods-1.4.0/)
=> Add swift_version to spec

Sources/ImageCache.swift
I noticed that the `KingfisherDidCleanDiskCache` changed from constant to variable in the [migration](https://github.com/kukushi/Kingfisher/commit/b35af72) to Swift 3.
IMO, this may be an unintended modification, because any changes to `KingfisherDidCleanDiskCache`'s value may lead to unexpected behaviors.
=> `KingfisherDidCleanDiskCache` should be a constant

Demo/Demo/Kingfisher-Demo/ViewController.swift, Sources/ImageDownloader.swift
This allows using network activity indicator correctly. Fixes https://github.com/onevcat/Kingfisher/issues/605
I have been using this my fork for some time and thought it would be good idea to merge it back to the official repo.
Maybe the naming could be better. Any ideas?
=> Add new method to ImageDownloaderDelegate - didFinishDownloadingImageForURL:with:error

Sources/String+MD5.swift
Using Kingfisher<Base> as String proxy is a better way, like UIImageView, UIImage, etc.
```
extension String: KingfisherCompatible { }
extension Kingfisher where Base == String
```
@onevcat
=> Replace  StringProxy with Kingfisher<Base>

Sources/KingfisherManager.swift, Sources/KingfisherOptionsInfo.swift, Tests/KingfisherTests/KingfisherManagerTests.swift
After downloading an image, we sometimes need to wait for caching to be completed so that we can copy the file or use the cache path for some other operations. This `waitForCache` option allows us to achieve that behavior.
Fixes #956
=> Add `waitForCache` option for waiting caching before returning the retrieved image

Sources/KingfisherManager.swift
I've used UUID instead of name as a suffix so that it won't break any existing projects using Kingfisher.
Fixes #975
=> Process images on a separate queue on `KingfisherManager`

Sources/AnimatedImageView.swift, Sources/ImageDownloader.swift
`Swift3` has already changed the keyword of class-only protocol, let's change to `AnyObject` as well.
=> Replace class-only protocol keyword with AnyObject

Sources/ImageDownloader.swift
I think we don't need to go on downloading data if the status code is invalid.
=> Cancel download task when response status code invalid

Sources/Image.swift, Tests/KingfisherTests/ImageExtensionTests.swift
In this PR I am passing `scale` property to `UIImage`s `init` method when the animated image is being created. This is needed to get gifs of proper size when loading from `NSDataAsset`.
=> Pass scale property when creating animated image on iOS

Sources/Extensions/ImageView+Kingfisher.swift, Sources/Extensions/NSButton+Kingfisher.swift, Sources/Extensions/UIButton+Kingfisher.swift, Sources/Extensions/WKInterfaceImage+Kingfisher.swift, Sources/General/KingfisherOptionsInfo.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift, Tests/KingfisherTests/NSButtonExtensionTests.swift, Tests/KingfisherTests/UIButtonExtensionTests.swift
**Use case**
Let's assume that we have an app with a list of users, with the following conditions:
* Each user could have an avatar, but we have also users without it.
* We don't wont to have empty gaps in UI for users without an avatar.
* We know how to create avatar URL for given user, but we are not sure if it will work properly or return 404 response.
* We would like to use the default image for users without an avatar.
**Could we use placeholder property?**
Nope. Because with placeholder user will see blinking placeholder image changing to the proper avatar (for the existing ones).
**Changelog**
☑️ Add `.onFailureImage(Image)` option to KingfisherOptionsInfo
☑️ Add support for this option in ImageView, UIButton, NSButton and WKInterfaceImage extensions
☑️ Add test cases to iOS & …
=> Add .onFailureImage(Image) option to set default image when loading request will be failed

Kingfisher.xcodeproj/project.pbxproj, Sources/General/KingfisherOptionsInfo.swift, Sources/Networking/RedirectHandler.swift, Sources/Networking/SessionDelegate.swift, Tests/KingfisherTests/KingfisherOptionsInfoTests.swift
Example of use:
1. Implement ImageDownloadRedirectHandler protocol:
extension NetworkManager: ImageDownloadRedirectHandler
{
func handleHTTPRedirection(for _: SessionDataTask, response _: HTTPURLResponse, newRequest: URLRequest, completionHandler: @escaping (URLRequest?) -> Void)
{
var modified = newRequest
modified.allHTTPHeaderFields = authorizationHeaders
completionHandler(modified)
}
}
2. Pass redirect handler as .redirectHandler option:
imageView.kf.setImage(with: url, placeholder: placeholder, options: [ .redirectHandler(NetworkManager.shared)])
=> Add redirect handler.

Sources/Networking/SessionDelegate.swift
=> Add lock to fix thread racing

Sources/Networking/ImagePrefetcher.swift, Tests/KingfisherTests/ImagePrefetcherTests.swift
Fix for #1109 
All prefetchers should share the same queue to prevent unlimited queue count, and it is enough to use the caller queue now (normally, the main queue). As a side effect, it also allows downloader being manipulated in the same queue.
The downloader and manager are not designed in a thread-safe behavior for better performance. So the callers are required to ensure the invocation happens in the same (main) queue.
=> Use the same queue for all prefetchers

Sources/General/Kingfisher.swift, Sources/Image/ImageFormat.swift, Sources/Utility/SizeExtensions.swift, Sources/Utility/String+MD5.swift
In the current master branch (and I believe, Kingfisher 5 generally), attempting to set Kingfisher attributes through the `kf` variable of `KingfisherCompatible` causes a compiler error:
```swift
class TestView: UIImageView {
func setUp() {
kf.indicatorType = .activity  // Error: cannot assign to property: 'self' is immutable
}
}
```
The reason for this is subtle. The `KingfisherCompatible` protocol is not class-specific, so it could be conformed to by a struct. Setters are implicitly `mutating`. And structs are allowed to reassign `self` inside of any mutating method. 
However, class instances do not allow the assignment of `self`. So when `KingfisherCompatible` is adopted by a class entity, the compiler does not allow access to the setter.
I know this sounds wacky; more details …
=> Bug fix: setting properties through kf extension causes compiler error

Sources/Cache/DiskStorage.swift, Tests/KingfisherTests/DiskStorageTests.swift
This option allows disabling md5 encryption for creation cache file name in DiskStorage.
=> Add an option for disabling encryption for a cache file name

Sources/General/ImageSource/Source.swift, Sources/General/KingfisherManager.swift, Sources/Networking/ImageDownloader.swift, Sources/Networking/ImagePrefetcher.swift, Tests/KingfisherTests/ImagePrefetcherTests.swift, Tests/KingfisherTests/KingfisherManagerTests.swift
Add `Source` support to `ImagePrefetcher`. Ref #1135
=> Feature source image prefetcher

Sources/Networking/ImagePrefetcher.swift
Fix stack overflow when prefetching large number of images that were already previously cached to disk. A regression to version 3.3.0.
Also improve consistency for dispatching to queues using the newer CallbackQueue enum.
=> Fix stack overflow regression with ImagePrefetcher

Sources/Networking/ImagePrefetcher.swift, Sources/Networking/SessionDataTask.swift, Sources/Networking/SessionDelegate.swift, Tests/KingfisherTests/ImagePrefetcherTests.swift, fastlane/Fastfile
This should fix the corrupted memory due to race condition introduced by Swift 5 compiler.
#1147 and #1148 should be fixed by these changes.
=> Fix prefetcher thread

Package.swift, README.md
This adds support for SwiftPM manifest based dependency managers. Specifically this adds support for installing via [Accio](https://github.com/JamitLabs/Accio) but will probably also work with SwiftPM once it's integrated into Xcode.
=> Update SwiftPM manifest file

Sources/Utility/Result.swift
I think that it's good time to hide custom Result type declaration for Swift 5 clients and switch to built-in type. For Swift 4.2 and older it will be still visible.
=> Use built in Result type on Swift 5

.gitignore, fastlane/Fastfile
As discussed in #1179 this PR updates the `release` Fastlane lane to upload a zip archive containing prebuild versions of Kingfisher to GitHub
=> Add prebuilt framework when releasing to GitHub

Sources/Utility/String+MD5.swift
I have a question，in "String+MD5.swift"，use “reduce” func may be better than use “map” and “joined” to create MD5 string by an [UInt8]，"map" may be cause space complexity O(n) ，it create a temp array [String]，Or are there other benefits to using "map" and "joined"?
=> Optimize MD5 String By `reduce` Function

Sources/General/Deprecated.swift, Sources/Image/ImageDrawing.swift, Sources/Image/ImageProcessor.swift, Sources/Utility/ExtensionHelpers.swift, Sources/Views/Indicator.swift
According to the official documentation (https://developer.apple.com/documentation/uikit/creating_a_mac_version_of_your_ipad_app),
```swift
#if !targetEnvironment(UIKitForMac)
// Code to exclude from Mac.
#endif
```
These AND conditions are added to support the compilation for Project Catalyst
=> Experimental: Support Project Catalyst

Package.swift, Sources/Extensions/NSButton+Kingfisher.swift, Sources/Extensions/UIButton+Kingfisher.swift, Sources/Extensions/WKInterfaceImage+Kingfisher.swift
As described in issue #1221 iOS app is unable to build because AppKit, UIKit and WatchKit wasn't conditionally imported in source files. I added `canImport` when it was necessary.
I need to add `platforms` to `Package.swift` to tell Xcode that it can use iOS 10 as development target for Kingfisher and fix a lot of "not available" errors.
=> Update code for Xcode 11 SPM

Sources/Utility/Result.swift
As a team who use this framework we have troubles with the Result extension. We have our own extension around Result with same properties. So we can't use our extension together with Kingfisher.
=> Remove deprecated Result extension

Sources/Extensions/NSButton+Kingfisher.swift, Sources/General/Deprecated.swift, Sources/Image/ImageDrawing.swift, Sources/Image/ImageProcessor.swift, Sources/Utility/ExtensionHelpers.swift, Sources/Views/AnimatedImageView.swift, Sources/Views/Indicator.swift
Minor changes introduced in Xcode 11 beta 4:
- `UIKitForMac` target environment is now called `macCatalyst`
- `UIActivityIndicatorView.Style.gray` has been renamed to `UIActivityIndicatorView.Style.medium` on Catalyst
-  `AnimatedImageView` needed `#if canImport(UIKit)` in order to import UIKit: [diff](https://github.com/onevcat/Kingfisher/compare/onevcat:80c0f2c...marcosgriselli:9c24f25#diff-632f8a05a77c7a6a3a289dcd86ae5b2dR34). Not sure if I was doing something wrong on my side for this one. 
I'm currently playing with a Catalyst project with beta 4 so I'm able to test anything that's needed.
=> Updates for Xcode 11 beta 4

Sources/Networking/ImageDownloader.swift
The `open` variant of `downloadImage(...)` is never called by Kingfisher while the `internal` one is. This removes the legacy variant and allows for subclassing of the modern one.
Open to ideas to retain the `deprecated` `downloadImage(...)` method.
=> subclassing fix for ImageDownloader

Demo/Demo/Kingfisher-Demo/ViewControllers/ProgressiveJPEGViewController.swift, Demo/Kingfisher-Demo.xcodeproj/project.pbxproj, Sources/Extensions/ImageView+Kingfisher.swift, Sources/Extensions/NSButton+Kingfisher.swift, Sources/Extensions/UIButton+Kingfisher.swift, Sources/Extensions/WKInterfaceImage+Kingfisher.swift
=> 修复各种扩展中`taskIdentifier`的线程安全问题 它在不同线程中调用可能出现崩溃问题

Sources/Image/Filter.swift, Sources/Image/ImageProcessor.swift, Tests/KingfisherTests/ImageProcessorTests.swift
=> Use `|>` for better precedence

Sources/Extensions/ImageView+Kingfisher.swift, Sources/Extensions/NSButton+Kingfisher.swift, Sources/Extensions/UIButton+Kingfisher.swift, Sources/Extensions/WKInterfaceImage+Kingfisher.swift, Sources/General/KingfisherError.swift, Sources/General/KingfisherManager.swift, Sources/General/KingfisherOptionsInfo.swift, Sources/Networking/ImagePrefetcher.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift, Tests/KingfisherTests/KingfisherManagerTests.swift, Tests/KingfisherTests/KingfisherOptionsInfoTests.swift
This implements what is mentioned in #1245 
It adds a new option `.alternativeSources([Source])` to allow you to set an array of `Source`s as an alternative for original loading. If the original `Source` loading fails, the value in this array will be used to continue the loading, until all `Source`s are used, then an `alternativeSourcesExhausted` error will be thrown out.
=> Feature alternative urls

Sources/Extensions/ImageView+Kingfisher.swift, Sources/Views/Indicator.swift
This fixes #1296 which turns out to be a regression of recent refactoring for the customized indicator.
=> Fix unconstraint size

Sources/General/KingfisherManager.swift
=> Make sure to skip disk cache when `fromMemoryCacheOrRefresh` set

Sources/Image/Image.swift, Sources/Image/ImageDrawing.swift
=> Fix processor and redraw orientation

Kingfisher.podspec
This seems to only be used by the SwiftUI sources so it doesn't need to
be at the top level.
=> Move podspec config to SwiftUI subspec

Sources/Cache/Storage.swift
=> Prevent 32bit int overflow when calculating duration forr day

Sources/Cache/CacheSerializer.swift, Sources/Image/Image.swift, Tests/KingfisherTests/KingfisherManagerTests.swift
=> Feature customizable default cache serializer

Sources/SwiftUI/KFImage.swift
This is a pull request to address the issue raised in #1383. KingfisherSwiftUI does not support local files in `KFImage()`. This seems like a simple and safe addition to support them.
=> Added support for local files to KFImage.

Sources/General/KingfisherManager.swift
I've enabled the thread sanitizer to check if everything was ok in my project, then I found an issue in this class.
To reproduce the issue, you need to make several calls to KingfisherManager, not sure if the options affect the reproducibility. Here is the code I am using:
```swift
let processor: RoundCornerImageProcessor = .init(cornerRadius: SpotlightManager.avatarTargetSize.width / 2.0,
targetSize: SpotlightManager.avatarTargetSize,
backgroundColor: .clear)
let options: [KingfisherOptionsInfoItem] = [.backgroundDecode,
.downloadPriority(URLSessionTask.lowPriority),
.callbackQueue(.dispatch(avatarQueue)),
.processor(processor),
.scaleFactor(UIScreen.main.scale),
.cacheSerializer(FormatIndicatedCacheSerializer.png),
.waitForCache,
.diskCacheExpiration(.expired)] …
```
=> Fixes race condition for State of CacheCallbackCoordinator

CONTRIBUTING.md
Trivial change of link for seeing existing issues and add new issue. Old one was redirecting to a 404 page.
=> Change contributing documentation

Kingfisher.xcodeproj/project.pbxproj
This should fix #1412 
But it would prevent the Catalyst demo to compile since the Xcode would not specify correct iOS SDK root for the frameworks used in a macOS Catalyst project.
=> Remove SDK root to make Carthage build for macOS

README.md
`UIView` doesn't have a `size` property.
You can get a view's size with `UIView.bounds.size` -- I assume that's what was intended here.
=> Fix DownsamplingImageProcessor example

Package.swift
This converts Kingfisher/KingfisherSwiftUI to a dynamic framework when building with SPM. It should fix #1418
=> Use dynamic framework for SPM

Package.swift
This is a PR related to #1418 and #1423. Xcode 11.4 is not doing well on determining which type of linking (dynamic or static) should be used.
Xcode 11.4 added a new diagnostic on detecting duplicated libraries (as static ones) for Swift Package libraries. The compiler will not be happy if Kingfisher is linked to two targets, with the error:
> Swift package product 'Kingfisher' is linked as a static library by {APP_TARGET} and {OTHER_TARGET}. This will result in duplication of library code.
This is only correct when you want to link `OTHER_TARGET` as static library, and finally, the symbols in `OTHER_TARGET` will be copied into the final binary. It will cause duplicated code in the final binary.
However, it is not likely a common case in iOS development. Usually, we use `OTHER_TARGET` as …
=> Expose all build configuration for SPM

Sources/General/KingfisherManager.swift
Issue: 
When using a ImageProvider, imageModifier is not applied to the provider provided image. ImageModifier does apply to subsequent access from the cache.
Not sure if this is the best way fixing this issue. Let me know.
=> fix issue with image modifier not working on provider provided images

Sources/General/KingfisherManager.swift, fastlane/Fastfile
=> Fix xcframework binary crach in Swift 5.2 compiler

Demo/Demo/Kingfisher-Demo/ViewControllers/ProcessorCollectionViewController.swift
=> [FIX].zero is invalid for `referenceSize`

Sources/Cache/DiskStorage.swift, Tests/KingfisherTests/ImageDownloaderTests.swift
This makes the cache map thread-safe for #1480
=> Anghami master

Sources/Cache/DiskStorage.swift
We use `ImageCache.isCached` on the main thread in our application and we noticed that it would sporadically cause the main thread to hang on I/O. Some investigation showed that this was due to 2 things.
1. A straight-up bug when building the file URL in `DiskStorage` which uses a variant of `URLByAppendingPathComponent:` that does disk I/O to figure out if the path it's building is for a directory or a file. In our case we know it's a file and this is completely unnecessary and we can simply use `URLByAppendingPathComponent:isDirectory:` and avoid this. 
2. While KingFisher's ultimate source-of-truth on whether an image is cached or not is whether the file exists on disk, it is possible to cheaply put an in-memory hash table check before doing so that filters out most unnecessary trips …
=> Reduce synchronous I/O when checking `ImageCache.isCached`

Sources/Cache/ImageCache.swift
Hi~ 👋 I'm glad to contribute toward `Kingfisher`
1. Add `clearCache`, `clenExpiredCache` function
`clearCache` -> Erase the cache data in memory and disk
`cleanExpiredCache` -> Erase the expired cache data in memory and disk
The inspiration for this idea came from [SDWebImage](https://github.com/SDWebImage/SDWebImage/blob/40023d566878027bc5780121e3435396785ffb96/SDWebImage/Core/SDImageCache.m#L845)
```swift
SDImageCache.shared.clearCache(.all)
```
2. Modify incorrect comment of `cleanExpiredMemoryCache`
`cleanExpiredMemoryCache` works synchronously, but comment says asynchronous
=> Add `clearCache`, `cleanExpiredCache` function

Kingfisher.xcodeproj/project.pbxproj, Sources/Extensions/NSTextAttachment+Kingfisher.swift, Sources/General/Kingfisher.swift
This will allow using Kingfisher on NSTextAttachment in an attributed label. I've followed the same format for other extensions that add compliance for KingfisherCompatible.
We can now add a image to a label using Kingfishers cache like this
```
// Create a label
let label = UILabel()
// Create a attributed string
let attributedText = NSMutableAttributedString(string: "some string")
// Create the text attachment
let textAttachment = NSTextAttachment()
// Set the size of the attachment
let capHeight = label?.font.capHeight ?? 0
textAttachment.bounds = CGRect(x: 0, y: -1, width: capHeight + 2, height: capHeight + 2)
// Request the image from Kingfisher
textAttachment.kf.setImage(with: url)
// Add the text attachment to the beging of the text attributedText …
```
=> Add extension to handle NSTextAttachment as KingfisherCompatible

Sources/SwiftUI/ImageBinder.swift, Sources/SwiftUI/KFImage.swift
And also ensure image setting on main thread
=> Move appear life cycle to placeholder

Sources/Networking/SessionDataTask.swift, Sources/Networking/SessionDelegate.swift
I maintain a couple of apps that uses your library to great success.
However there are an annoying crash that happens in both apps - even though the actual implementation of cancelling download tasks is very different in the apps.
A simple way it can be replicated would be to do this:
`func collectionView(_ collectionView: UICollectionView, didEndDisplaying cell: UICollectionViewCell, forItemAt indexPath: IndexPath) {
if let cell = cell as? TestCell {
cell.imageView.kf.cancelDownloadTask()
}
}`
In that case - if you have a long list - so you can get your scrolling velocity high and maintain that velocity it will eventually crash.
From my debugging the cause seems to be that since the underlying _URLSessionDataTask_ is cancelled prior to the callback then it can actually have become nil …
=> Cancel moved to avoid crash

Demo/Demo/Kingfisher-Demo/Base.lproj/Main.storyboard, Demo/Demo/Kingfisher-Demo/ViewControllers/AVAssetImageGeneratorViewController.swift, Demo/Demo/Kingfisher-Demo/ViewControllers/GIFViewController.swift, Demo/Demo/Kingfisher-Demo/ViewControllers/HighResolutionCollectionViewController.swift, Demo/Demo/Kingfisher-Demo/ViewControllers/ImageDataProviderCollectionViewController.swift, Demo/Demo/Kingfisher-Demo/ViewControllers/IndicatorCollectionViewController.swift, Demo/Demo/Kingfisher-Demo/ViewControllers/InfinityCollectionViewController.swift, Demo/Demo/Kingfisher-Demo/ViewControllers/NormalLoadingViewController.swift, Demo/Demo/Kingfisher-Demo/ViewControllers/ProcessorCollectionViewController.swift, Demo/Demo/Kingfisher-Demo/ViewControllers/ProgressiveJPEGViewController.swift, Demo/Demo/Kingfisher-Demo/ViewControllers/TextAttachmentViewController.swift, Demo/Demo/Kingfisher-Demo/ViewControllers/TransitionViewController.swift, Demo/Demo/Kingfisher-macOS-Demo/ViewController.swift, Kingfisher.xcodeproj/project.pbxproj, Sources/Extensions/ImageView+Kingfisher.swift, Sources/Extensions/NSButton+Kingfisher.swift, Sources/Extensions/NSTextAttachment+Kingfisher.swift, Sources/Extensions/UIButton+Kingfisher.swift, Sources/Extensions/WKInterfaceImage+Kingfisher.swift, Sources/General/KF.swift, Sources/General/KingfisherOptionsInfo.swift, Sources/Image/ImageProcessor.swift, Sources/Image/ImageProgressive.swift, Sources/Image/Placeholder.swift, Sources/Networking/ImageDownloader.swift, Sources/Networking/ImagePrefetcher.swift, Sources/Networking/RedirectHandler.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift, Tests/KingfisherTests/UIButtonExtensionTests.swift
=> Feature KF builder

Sources/Networking/ImageDownloader.swift, Sources/Networking/SessionDataTask.swift, Sources/Networking/SessionDelegate.swift, Tests/KingfisherTests/RetryStrategyTests.swift
This patch adds/adjusts some lock behaviors. This should help to avoid racing for accessing originalRequest properties and fix #1511
=> Avoid racing for accessing originalRequest

Sources/SwiftUI/ImageBinder.swift
This should fix #1567 
Some tests would be added in the future to prevent this from happening again.
=> Call the completion handler in next main

Sources/General/KingfisherOptionsInfo.swift, Sources/Networking/ImageDownloader.swift, Sources/Networking/RequestModifier.swift, Tests/KingfisherTests/ImageDownloaderTests.swift
This covers #1501 and provides a way with less breaking of the current APIs.
=> Feature async request modifier

Sources/General/KFOptionsSetter.swift, Sources/General/KingfisherError.swift, Sources/General/KingfisherManager.swift, Sources/General/KingfisherOptionsInfo.swift, Sources/Networking/ImageDownloader.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift, Tests/KingfisherTests/Utils/StubHelpers.swift
This implements #1417. Now a new option `lowDataMode` is added to support loading another source when the Low Data Mode is turned on and the original source request fails.
=> Feature Low Data Mode

Sources/SwiftUI/KFImage.swift
=> Start binder when KFImage init as a workaround before StateObject

Kingfisher.podspec
After upgrading to Kingfisher 6, our app got crashed on iOS 12 device. (ipa was archived in Xcode 12.3) 
Here is the log:
It seems like Xcode did not handle this correctly, and got "strong" link to SwiftUI. This bug [should have fixed in Xcode 11.1](https://stackoverflow.com/a/60198305), but somehow triggered with Kingfisher 6.
It is good to have an more explicit declaration on podspec file, to tell Xcode should weakly link to SwiftUI and Combine. I test it on my device and it works fine.
=> Fix SwiftUI link

Kingfisher.podspec
kingfisher can't be build to static library in `swift` and `Objective-C` mixed project, the error is shown below picture
set "Kingfisher.h" private that will not be in umbrella then can support to compile with no `use_framework!`
-------
在混编环境中不开启`use_framework!`的情况下如果直接引入`Kingfisher`，在伞文件中会报出如上图中的错误（头文件找不到）。
这个问题一般出现在`OC`与`Swift`共存的`pod`中;
`source_files`中的文件默认为`public`的，`public`的`OC`头文件会自动被放到伞文件中，然后在不开启`use_framework`的环境中编译就会报错，所以我把这个`OC`的头文件标记为`private`了，目的是不让`Kingfisher.h`这个头文件出现在`umbrella`文件中，这样在不打开`use_framework`的环境下（即把`kingfisher`编译为静态库）也能正常编译通过了
=> support be compile with no use_framework! in podfile

Sources/Cache/ImageCache.swift, Sources/General/KingfisherManager.swift, Sources/Networking/ImageDataProcessor.swift, Sources/Networking/ImageModifier.swift, Tests/KingfisherTests/ImageCacheTests.swift, Tests/KingfisherTests/ImageDownloaderTests.swift, Tests/KingfisherTests/KingfisherManagerTests.swift
=> Fix image modifier cache

Demo/Demo/Kingfisher-Demo/SwiftUIViews/SwiftUIList.swift, Demo/Demo/Kingfisher-Demo/SwiftUIViews/SwiftUIView.swift, Sources/Extensions/ImageView+Kingfisher.swift, Sources/General/ImageSource/Source.swift, Sources/General/KF.swift, Sources/General/KFOptionsSetter.swift, Sources/Image/ImageTransition.swift, Sources/SwiftUI/ImageBinder.swift, Sources/SwiftUI/KFImage.swift, Sources/SwiftUI/KFImageOptions.swift
This avoids the `@ObservedObject` resetting problem.
=> Use `@State` for KFImage state management

Sources/SwiftUI/ImageBinder.swift
=> Correct hash implementation for image binder

Sources/Cache/DiskStorage.swift, Sources/Cache/ImageCache.swift, Sources/General/KingfisherError.swift
=> Fix cache crash when no disk space left

Sources/SwiftUI/ImageBinder.swift
=> Use weak image for image binder to prevent unintended holding

Sources/Networking/ImageDownloader.swift, Sources/Networking/SessionDelegate.swift, Tests/KingfisherTests/ImageDownloaderTests.swift
https://github.com/onevcat/Kingfisher/issues/1619
尝试一种方案。把URLSessionDataDelegate的其他协议方法，转发给业务方定制化处理
=> 有没有好的方案，把URLSessionDataDelegate更多的协议实现暴露出来

Sources/Cache/DiskStorage.swift, Sources/Cache/ImageCache.swift, Sources/Cache/MemoryStorage.swift, Tests/KingfisherTests/ImageCacheTests.swift, Tests/KingfisherTests/ImagePrefetcherTests.swift, Tests/KingfisherTests/MemoryStorageTests.swift
=> Mark memory and disk storage as `public`

Sources/Image/Image.swift, Tests/KingfisherTests/ImageExtensionTests.swift
Refs. #1645
This PR adds the property `imageFrameCount` to the a `KFCrossPlatformImage`. This property is an optional _Int_ and it's set by default when an animated image is created. Since the `KFCrossPlatformImage` already stores an `imageSource` we can retrieve easily the frame count and store it.
This property is the equivalent of `animatedImageFrameCount` used in `SDAnimatedImage`
I didn't set the property as read only to give the possibility to custom processors to also set the value.
- Unit test should be 🟢
=> Add imageFrameCount

Sources/Networking/ImageDownloader.swift, Sources/Networking/ImageDownloaderDelegate.swift
Changed `imageDownloader(_:didDownload:for:)` to `imageDownloader(_:didDownload:with:)` accepting the returned URLResponse from the request.
This allows modifying the image data (like decrypting) based on the response the server sends (for example a specific header)
=> Modify ImageDownloaderDelegate to accept URLReponse

Demo/Demo/Kingfisher-Demo/Base.lproj/Main.storyboard, Demo/Demo/Kingfisher-Demo/ViewControllers/GIFHeavyViewController.swift, Demo/Kingfisher-Demo.xcodeproj/project.pbxproj, Kingfisher.xcodeproj/project.pbxproj, Sources/Image/GraphicsContext.swift, Sources/Image/ImageDrawing.swift, Sources/Views/AnimatedImageView.swift
There are several things I did :) 
**GIFHeavyViewController**
Contains an example that I used for testing. Previously this controller was causing crashes on my iPhone X.
**GraphicsContext**
An enum with static functions to handle logic for begin/context/end. Basically it is a copy of the code from the ImageDrawing. But this way the code could be reused both inside Animator and ImageDrawing. Right now I use it only for the code that I implemented. But if you feel like keeping this component I can update ImageDrawing. I hope GraphicsContext doesn't break Mac OS implementation. Tell me if I messed up something 😄 
**Animator**
To fix the crash I came with an idea, that the crash occurs due to the fact that CGContext gets freed when we still try to use it. And I assumed that this could happen …
=> [FIX] Crash for GIF with a lot of frames

Sources/SwiftUI/KFImage.swift
Hello. I have the bug on Mac catalyst. Added a little bit fix
=> added an attribute to fix error on mac catalyst

CONTRIBUTING.md
A simple fix for a link that was referencing to 404 page.
=> Fixes broken link in contributing documentation

Sources/Utility/CallbackQueue.swift, Tests/KingfisherTests/KingfisherTestHelper.swift
Usually return nothing is written as () -> Void.
However, in some places, it is written as ()->() expression.
How about editing for conventions?
=> Modified for convention

Sources/Image/GIFAnimatedImage.swift, Sources/Image/Image.swift, Sources/Views/AnimatedImageView.swift
I'm working on a feature for my app that shows a progress bar below gifs and videos.
In order to animate the bar I need to know a couple more things about the animated image view and gif that aren't currently exposed.
The only functional change here is calling didPlayAnimationLoops *after* the loop completes (unless it plays to the end and stops). I believe this is what consumers would expect (at least, it's what I expected). This is necessary because I need to restart the progress bar animation when the gif loops back to the beginning, and currently this delegate method is being called while the gif is still showing the last frame.
=> Expose AnimatedImageView fields to allow consumers to observe GIF progress

Sources/Cache/DiskStorage.swift, Sources/Cache/ImageCache.swift, Sources/General/KingfisherOptionsInfo.swift
Straw-man proposal for providing more writing options for store operation as per discussion here https://github.com/onevcat/Kingfisher/discussions/1792.
**My question:**
I am wondering what would be the best way to pass any additional attributes to the `DiskStorage`? One of the requirements that we currently have for one of the projects - is to have `.complete`(FileProtectionType) protection as we need to ensure that any data we're storing on disk is encrypted at rest - at least when the device is locked.
**Proposed API:**
```swift
...
kf.setImage(with: url,
placeholder: placeholder,
options: [.diskStoreWriteOptions([.atomic, .completeFileProtection])])
...
```
Where new image resources for the `url` path will have `.atomic` & `.completeFileProtection` [writing …
=> Added Writing options for diskStorage store operation

CHANGELOG.md, Sources/Views/AnimatedImageView.swift
closes #1804 
The `AnimatedImageView` is crashing on iOS 13 and below. (See issue)
This fix is branching iOS 15 off, so that it will work for < iOS 13 and > iOS 13.
=> Fixed animated image view for iOS 13 and below

Sources/Views/AnimatedImageView.swift
https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes
From Xcode 13 Release Notes;
> Availability checks in iPhone and iPad apps on a Mac with Apple silicon always return true. This causes iOS apps running in macOS 11 Big Sur to see iOS 15 APIs as available, resulting in crashes. This only affects apps available in the Mac App Store built with the “My Mac (Designed for iPhone)” or “My Mac (Designed for iPad)” run destination. It doesn’t affect Mac Catalyst apps. (83378814)
> 
> Workaround: Use the following code to check for iOS 15 availability:
>        ` if #available(iOS 15, *), ProcessInfo.processInfo.operatingSystemVersion.majorVersion >= 15 {`
=> Fixed iOS 15 availability check for M1.

Sources/SwiftUI/ImageBinder.swift, Sources/SwiftUI/KFImageRenderer.swift
This fixes #1821 
Currently the loading will not start until the `onAppear` of the placeholder shown, which is too late for a sync loading from disk or memory. It causes an unwanted flickering. This PR moves the loading starting earlier to the beginning of `KFImageRenderer.body`. The loading method call (and its states in `ImageBinder`) is protected by the main thread, so it would not actually run more than once, which should be pretty light.
Also added a `loading` property to prevent situations that image loading without an actual downloading process (say, applying a processor to a cached image). Before this fix, it will be recognized as "not `loadingOrSucceeded`" and triggers multiple start loading behaviors since the `body` will be evaluated for multiple times.
=> Start loading when evaluating view

Sources/General/ImageSource/ImageDataProvider.swift, Sources/General/ImageSource/Resource.swift, Tests/KingfisherTests/ImageDataProviderTests.swift
=> Use a stable default cache key for local files

Sources/General/KF.swift
I ran into some issues compiling `master` related to some recent CarPlay merges due to this error:
```
Kingfisher/Sources/General/KF.swift:230:28: 'setImage(with:placeholder:parsedOptions:progressBlock:completionHandler:)' is only available in iOS 14.0 or newer
```
Context:
- Xcode 13
- iOS 14+ target app & app extension
- M1 dev box
I noticed [you fixed this elsewhere](https://github.com/onevcat/Kingfisher/commit/2bec5cd9f046ceee21e7965b8367c43073905c27) recently and I think it applies here too.
Thank you for Kingfisher!
(distant relative of #1827)
=> Fixes incorrect `@available` for a flavour of `setImage`

Sources/General/KFOptionsSetter.swift, Tests/KingfisherTests/KingfisherOptionsInfoTests.swift
A follow up for https://github.com/onevcat/Kingfisher/pull/1793
After adding `diskStoreWriteOptions` to `KFOptionsSetter` we now able to add writing options to `KFImage` (SwiftUI) component with a following code:
``` swift
KFImage(ImageLoader.sampleImageURLs.first)
.diskStoreWriteOptions([.completeFileProtection])
```
As well as updated tests that I missed during my previous PR. Please let me know if there are any changes you would like me to make @onevcat 👍
=> Updating KFOptionSetter with diskStoreWriteOptions

Sources/SwiftUI/ImageBinder.swift
This should fix an issue mentioned here: https://github.com/onevcat/Kingfisher/issues/1849#issuecomment-975062148
When `animation` is nil, it seems that using of `withAnimation(animation)` cannot guarantee the value is available and "published" correctly by the `@Published` wrapper. So the `ImageRenderer` does not catch it and renders an 0.0 opacity incorrectly.
This patch fixes this case by checking the animation, as well as calling it ahead.
=> Move animation setting before image setting

Sources/Image/Image.swift
[Addressing issue #1880](https://github.com/onevcat/Kingfisher/issues/1880)
When we calculate the Image cost for cache purposes, we should take into account how many frames make up the Image to get an accurate cost.
=> [Issue #1880] - Image cost should account for number of image frames

Sources/General/ImageSource/Resource.swift, Tests/KingfisherTests/ImageDataProviderTests.swift
This should be a fix for #1902
=> Fix wrong key override when created by `ImageResource`

Sources/General/ImageSource/ImageDataProvider.swift, Sources/General/ImageSource/Resource.swift, Tests/KingfisherTests/ImageDataProviderTests.swift
This allows users get the correct default cache key even for file URL.
This fixes https://github.com/onevcat/Kingfisher/issues/1825#issuecomment-1052589055
=> Give correct cache key for local urls

Sources/Extensions/ImageView+Kingfisher.swift, Sources/SwiftUI/ImageBinder.swift, Sources/SwiftUI/KFImageRenderer.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift
This fixes an issue where custom Placeholders are never removed when an error occurs even when there is an Error Image that should be shown instead.
Steps to reproduce:
1. Add custom placeholder
2. Add Error Image
3. Load image with an Error
4. Placeholder always shows because it is never removed
*Note*: Unit Test added for UIKit failed without fix and passes with fix
=> Error image with custom Placeholder fix

Sources/General/KingfisherManager.swift
The animated image might be loaded in different options. Try to reload the representation.
This fixes #1923
=> Choose to recreate animated image

Sources/Views/AnimatedImageView.swift
Fix a crash report in this thread https://github.com/onevcat/Kingfisher/issues/1844
Add a workaround to ensure the image instance dealloc in main thread.
=> Fix a crash on AnimatedImageView

.gitignore
On June 13, 2016, at WWDC16, OS X was renamed macOS.
But here in the gitignore file this hasn't changed.
Plz merge it
=> [UPDATE] OSX > macOS in gitignore

Sources/SwiftUI/KFImageRenderer.swift
Fix #1972 
If `EmptyView` is used as placeholder, it does not load due to `Group { EmptyView() }` is eliminated and does not trigger `onAppear`.
=> Overlay the placeholder view to allow onAppear executing

Demo/Demo/Kingfisher-Demo/SwiftUIViews/SingleViewDemo.swift, Sources/SwiftUI/KFImageRenderer.swift
And this now should align to `AsyncImage`'s layout behavior:
- When not setting a placeholder, `KFImage` takes all available space while loading.
- When a placeholder is set, `KFImage` takes the same layout of the placeholder.
- After loaded, it respects the image's intrinsic size.  
This should fix #1721 again and keep the `EmptyView` loading behavior as in #1972.
=> Respect layout behavior when explicit placeholder is given

Demo/Demo/Kingfisher-Demo/SwiftUIViews/MainView.swift, Demo/Demo/Kingfisher-Demo/SwiftUIViews/SingleListDemo.swift, Demo/Kingfisher-Demo.xcodeproj/project.pbxproj, Sources/SwiftUI/KFImageRenderer.swift
This fixes #1988 
The reason is not quite clear yet, but it seems that SwiftUI on iOS 16 is failing to call the `onAppear` when the view is deeply embedded in a list cell. By force adding an empty `onAppear`, it starts to be recognized again.
=> Fix SwiftUI life cycle when in List 

Sources/General/KingfisherManager.swift, Tests/KingfisherTests/KingfisherManagerTests.swift
As for #1409 it adds a `data` property to get the image data from result easier. 
```swift
imageView.kf.setImage(with: url) { result in
let data = try? result.get().data()
}
```
However, since the current image cache does not require a data to use, it requires a serialize of image to get the data, which might cause unnecessary performance cost when the images are loaded from cache (when loading from network, the downloaded data is contained in the result so everything is smooth). Changing this behavior would require a change to the public APIs and it has to be postponed to a major version release later.
=> A data reader in `RetrieveImageResult`

fastlane/Fastfile
This should be the preferred way to contain `dSYM` files now for xcframework.
=> Use xcframework and contain debug symbol inside the bundle

Sources/Cache/CacheSerializer.swift, Sources/General/KingfisherManager.swift, Tests/KingfisherTests/ImageProcessorTests.swift, Tests/KingfisherTests/KingfisherManagerTests.swift
This allows the processor to apply again if the original data is cached & used instead of the processed image data stored on the disk. 
#1912
=> Add `originalDataUsed` to serializer

Sources/General/KFOptionsSetter.swift, Sources/SwiftUI/ImageContext.swift, Sources/SwiftUI/KFImageOptions.swift, Sources/SwiftUI/KFImageRenderer.swift
=> Add an option to start image loading before view appear

Sources/Cache/DiskStorage.swift
This fixes an issue when you create a custom DiskStorage.Config instance and lose a possibility to configure a 'cachePathBlock'
=> Make ‘cachePathBlock’ public

Sources/SwiftUI/KFImageRenderer.swift
When building under the swift-5.8 development snapshot dated 2/9/2023, I get this error:
```
…/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageRenderer.swift:48:63: error: initializer for conditional binding must have Optional type, not 'AnyView'
if let placeholder = context.placeholder, let view = placeholder(binder.progress) {
^          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This PR fixes that, seems to work for both Xcode 14.2 (5.7?) and Swift 5.8 toolchains. Should be applied to 7.6 branch as well as master.
=> Fix 'initializer for conditional binding must have Optional type…' error

Sources/SwiftUI/ImageBinder.swift, Sources/SwiftUI/KFImageRenderer.swift
Especially when startLoadingBeforeViewAppear is true.
This should improve the general performance a bit and fix #2035
=> Fine-tune for the image rendering trigger

Sources/General/KingfisherError.swift, Sources/Networking/ImageDownloader.swift, Sources/Networking/ImageDownloaderDelegate.swift, Sources/Networking/SessionDelegate.swift, Tests/KingfisherTests/ImageDownloaderTests.swift, Tests/KingfisherTests/Utils/StubHelpers.swift
A generic way to implement #2043 
This adds a delegate method below:
```swift
protocol ImageDownloaderDelegate {
func imageDownloader(
_ downloader: ImageDownloader,
didReceive response: URLResponse,
completionHandler: @escaping (URLSession.ResponseDisposition) -> Void)
}
```
It is not possible to setup a delegate for the `ImageDownloader` and determine a response disposition when a response is received. Some example usage:
```swift
class ViewController: UIViewController {
override func viewDidLoad() {
super.viewDidLoad()
ImageDownloader.default.delegate = self
}
}
extension ViewController: ImageDownloaderDelegate {
func imageDownloader(_ downloader: ImageDownloader, didReceive response: URLResponse, completionHandler: @escaping (URLSession.ResponseDisposition) -> Void) {
guard let …
```
=> Feature response delegate

Sources/Image/Image.swift
I fixed warning `Heterogeneous collection literal could only be inferred to '[CFString : Any]'; add explicit type annotation if this is intentional`
Issue: #2059
=> fix add explicit type warning

Sources/Image/ImageProcessor.swift
fix warning `Class property 'black' cannot be used in a default argument value because 'UIKit' was not imported by this file; this is an error in Swift 6`
Issue #2062
=> fix warning 'UIKit' was not imported

Sources/General/ImageSource/Source.swift
Source.Identifier.current is a unique value for data processing in UI Components.
this value can be generated using Source.Identifier.next(),
it can also be modified outside of its scope.
To prevent modification of current properties outside of its scope, it is safer to mark it as private(set).
=> modified Source.Identifier.current access modifier

Sources/Views/AnimatedImageView.swift
This is a workaround for apple/swift issue 66015 (https://github.com/apple/swift/issues/66015), to allow xcframework built for tvOS.
=> Override initializers for tvOS

Sources/Image/GIFAnimatedImage.swift, Sources/Image/Image.swift, Sources/Image/ImageDrawing.swift, Sources/Views/AnimatedImageView.swift
Before this update, third-party image processors were unable to create animated images without relying on `UIImage.animatedImage`, which is only available on iOS and can consume a significant amount of memory. 
This pull request addresses the problem by introducing a new protocol called `ImageFrameSource` and refactoring `AnimatedImageView` to utilize it.
Relevant issue:
https://github.com/yeatse/KingfisherWebP/issues/41
https://github.com/yeatse/KingfisherWebP/issues/39
=> Introduce a custom image source provider to enable third-party image processors to utilize AnimatedImageView.

Sources/General/KingfisherManager.swift, Tests/KingfisherTests/KingfisherManagerTests.swift
When loading an animated image from the cache, Kingfisher will recreate it using the cached data. To avoid loading failures due to unsupported format with the default processor, we must ensure that the specified processor is always used.
=> fix: always use specified processors to recreate animated image representation

Sources/Networking/ImageDownloader.swift
In order to be able to implement a customized `ImageDownloader` I need to be able to create an `ImageDownloadResult` outside of the framework itself. Because the struct has no public init defined so far, there is no way for me to create a result in my customization. So I simply added the public init here.
Background:
In my app we use as custom scheme, like `myappasset://` in order to display images that are added as assets to the app's bundle. The view layer just has URLs for all image types, either a bundled one (`myappasset://someiconname`) or a normal remote URL (`https://somewebsite.com/image.png`). My first idea was to add a custom `ImageDataProvider`, but that would have made it necessary to either
- evaluate the URL type (asset or remote) with every `kf.setImage()` call, or
- …
=> Added a public init to ImageDownloadResult

Sources/General/ImageSource/AVAssetImageDataProvider.swift, Sources/General/KF.swift, Sources/Image/Image.swift, Sources/Image/ImageDrawing.swift, Sources/Image/ImageTransition.swift, Sources/Networking/ImageModifier.swift, Sources/Views/AnimatedImageView.swift, Sources/Views/Indicator.swift, Tests/KingfisherTests/ImageCacheTests.swift, Tests/KingfisherTests/ImageDownloaderTests.swift, Tests/KingfisherTests/ImageExtensionTests.swift, Tests/KingfisherTests/ImageModifierTests.swift, Tests/KingfisherTests/KingfisherManagerTests.swift, Tests/KingfisherTests/KingfisherOptionsInfoTests.swift, Tests/KingfisherTests/KingfisherTestHelper.swift
This PR fixes an issue where Kingfisher no longer compiles with Xcode 15 beta 6.
Up until Xcode beta 5, any changes wrapped in `#if os(iOS) ... #endif` would be included on visionOS, however, that is no longer the case in beta 6. Therefore we need to ensure that any existing iOS-specific code paths are included on visionOS.
=> Includes iOS-specific code paths on visionOS

Kingfisher.podspec, Kingfisher.xcodeproj/project.pbxproj, Package@swift-5.9.swift
This allows Xcode to generate read and generate the report based on Kingfisher's privacy manifest
> Although for now, it only reads the "collecting data" section and Kingfisher does not has one, so there should be no actual affect to the app project. But I can verify the relate file are already under the correct place and be checked by Xcode 15. So in future, if Xcode decides to also generate the report for `NSPrivacyAccessedAPITypes` one day, there should be no additional work required in Kingfisher side.
Ref: #2122 #2155
=> Actually add the privacy manifest to app resource bundle

Sources/Views/AnimatedImageView.swift
`UIScree.main` will be deprecated in a future version of iOS.
I used `UIAplication` to get display's scale.
developer doc > [mian](https://developer.apple.com/documentation/uikit/uiscreen/1617815-main) already deprecated. It causes serious errors in the near future.
So have to change another way. And `UIApplication` is the one way of getting display's scale. That is available from `iOS 13.0`. This is why control flow has `iOS 13.0` condition.
=> Use `UIApplication` instead of `UIScreen.main` on iOS 13.0 and later

Sources/General/ImageSource/AVAssetImageDataProvider.swift, Tests/KingfisherTests/ImageDataProviderTests.swift
In #1825, we fixed an issue that the cache does not work for local files when debugging: the reason was Xcode is trying to copy the app to a new sandbox location when debugging. So the resources inside the app bundle has a different local file URL.
In that issue, we fixed the cases for local images, but not yet for the `AVAssetImageDataProvider`, which still used the plain `absoluteString` as the cache key. Here we switched to use the `url.cacheKey`, which also considering the sandbox changing into account.
This should fix #2002
=> Use the correct cacheKey of local files for `AVAssetImageDataProvider`

Sources/SwiftUI/ImageBinder.swift
This can be considered an edge case and fixes #2167 
If the failure image exists, it will be set with `loadedImage` and not trigger the binder loading again. So there should be no need to send the change event in the general failure case (since there is nothing to update). This avoid unnecessary rendering and a case when `startLoadingBeforeViewAppear` is set (and loading errored).
=> Do not trigger view refresh if loading failure

Sources/Extensions/CPListItem+Kingfisher.swift
Fix compilation with Xcode 12.4
=> Fix compilation with iOS SDK 14.0-14.4

fastlane/Fastfile
=> Keep symlinks while creating xcframework zip

Sources/Image/Image.swift
- Added space in the comment: "//Flip image one more time if needed to, this is to prevent flipped image"
- Added a space between "//" and the text in the comment to maintain consistency with the existing comment style.
This change aims to improve code readability and maintain consistency.
I hope this helps. Please review when you get a chance.
=> Comment Modification - Adding Space

Sources/Utility/Runtime.swift
It is a swift bug, In iOS 13 or earlier versions. 
cast an Any? to protocol will always get nil
[https://stackoverflow.com/questions/42033735/failing-cast-in-swift-from-any-to-protocol](url)
In my case i use backgroundDecode option when download image, and if the image is a GIF the animate will lost, because the `decode` func not return itself
```
public func decoded(scale: CGFloat) -> KFCrossPlatformImage {
// Prevent animated image (GIF) losing it's images
#if os(iOS)
if frameSource != nil { return base }
#else
if images != nil { return base }
#endif
....... ........
}
```
The `frameSource` always get nil, because the `T` in  `getAssociatedObject` func is `ImageFrameSource` it is a protocol, so always return nil
```
func getAssociatedObject<T>(_ object: Any, _ key: UnsafeRawPointer) -> …
```
=> fix Any? cast to protocol always nil in ios 13

Sources/Image/ImageDrawing.swift, Sources/Views/AnimatedImageView.swift
Additional fix for #1844, where the context actually could not be retrieved.
=> Use the unretained version of CGImage to avoid racing

Sources/Cache/DiskStorage.swift
Much of the `DiscStorage.Backend` functionality was made public after this issue was raised https://github.com/onevcat/Kingfisher/issues/1602
`removeSizeExceededValues` is still `internal` and is not directly used anywhere within the class. As such, the sizeLimit set on the on the DiscStorage.Config is not respected.
I've created a fork do this for now - it would be great if this could be added.
=> make removeSizeExceededValues public in disc storage

Tests/KingfisherTests/ImageExtensionTests.swift
In Xcode 15.3 and Swift 5.10, below code does not return `nil` if `kCGImageSourceThumbnailMaxPixelSize` is 0. It returns some image size `64*64` . I am not sure why and it does not make any sense. Maybe a bug from Apple?
```
let downsampleOptions: [CFString : Any] = [
kCGImageSourceCreateThumbnailFromImageAlways: true,
kCGImageSourceShouldCacheImmediately: true,
kCGImageSourceCreateThumbnailWithTransform: true,
kCGImageSourceThumbnailMaxPixelSize: 0 // even we set it to 0
]
public func CGImageSourceCreateThumbnailAtIndex(_ isrc: CGImageSource, _ index: Int, _ options: CFDictionary?) -> CGImage?
```
Before fixing:
I just fix the test fail by assert with image size 64*64 and it's passed.
=> Fix testDownsamplingWithEdgeCaseSize fail

Sources/Utility/String+MD5.swift, Tests/KingfisherTests/DiskStorageTests.swift
Hello, I found when use `autoExtAfterHashedFileName = true`, the original method `var ext: String?` of finding the last "." to determine the extension is not effective because the field after the "@" symbol may contain a "com.onevcat.Kingfisher.xxx" and even include decimal points.
hope this PR is helpful.
=> UsesHashedFileNameWithAutoExtAndProcessor does not retrieve the correct file extension.

Sources/SwiftUI/ImageBinder.swift, Sources/SwiftUI/ImageContext.swift, Sources/SwiftUI/KFImageOptions.swift, Sources/SwiftUI/KFImageRenderer.swift
I was missing this option, seem to make a difference.
=> reducePriorityOnDisappear, flag to reduce download task priority.

Kingfisher.xcodeproj/project.pbxproj
As Swift Package Index server is trying to build the package with Xcode 15, setting the swift version in the scheme would fail the build, without bringing obvious benefit to Kingfisher, I guess it is better to keep it to Swift 5.0 for a while more.
Locally, we can set to 6.0 to make sure to get warnings from the new compiler and language version.
=> Set Swift 5 for default language mode

Sources/Cache/ImageCache.swift, Sources/General/ImageSource/AVAssetImageDataProvider.swift, Sources/General/ImageSource/PHPickerResultImageDataProvider.swift, Sources/General/Kingfisher.swift, Sources/Utility/DisplayLink.swift, Tests/KingfisherTests/DiskStorageTests.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift, Tests/KingfisherTests/MemoryStorageTests.swift
`@retroactive` is necessary when compiling with Swift 6, regardless of whether it's on Swift 5 mode.
=> Change `swift(>=6)` to use `compiler`

Sources/Image/GraphicsContext.swift, Sources/Image/ImageDrawing.swift
This fixes #2200 with another (identical) implementation for blur image method. Now a pure CG based way is used so it won't use the deprecated `UIGraphicsBeginImageContextWithOptions` and related context methods anymore.
=> Rewrite the blur rendering method without deprecated UIGraphicsBeginImageContextWithOptions

Sources/Utility/Runtime.swift, Sources/Views/AnimatedImageView.swift
Update links for repositories moved to the swiftlang org on GitHub
Update the link
+ https://github.com/apple/swift/ => https://github.com/swiftlang/swift/
+ https://github.com/apple/swift-evolution/ =>  https://github.com/swiftlang/swift-evolution/
Correct the reference
+ https://github.com/apple/swift/ => https://github.com/swiftlang/swift/
+ https://github.com/apple/swift-evolution/  =>  https://github.com/swiftlang/swift-evolution/
=> Update links for repositories moved to the swiftlang org on GitHub

.github/workflows/build.yaml, Sources/Image/Image.swift
=> Fix for Swift 5.9 compiler

.github/workflows/test.yaml, fastlane/Fastfile
Only run test in the last two supported Xcode versions. This saves some CI resources.
=> Split CI tasks to build and test

Sources/Image/ImageDrawing.swift
The regression has been likely caused by this PR:
- https://github.com/onevcat/Kingfisher/pull/2274
<table>
<tr>
<th align="center">
<p> 
<small>
ORIGINAL
</small>
</p>
</th>
<th align="center">
<p> 
<small>
BLURRED v8.0.0-8.0.1
</small>
</p>
</th>
<th align="center">
<p> 
<small>
BLURRED FIX
</small>
</p>
</th>
</tr>
<tr>
<td align="center">
</td>
<td align="center">
</td>
<td align="center">
</td>
</tr>
</table>
=> fix: The image doesn't render correctly when blur is applied

Sources/Image/ImageTransition.swift
Warning occurs when set `imageView.image` in animation closure of custom transition.
```swift
let transition = .custom(duration: 0.2, options: .curveEaseIn, animations: { imageView, image in
imageView.image = image
//  Main actor-isolated property 'image' can not be mutated from a Sendable closure; this is an error in the Swift 6 language mode
}, completion: nil)
```
So I added `@MainActor` attribute to animations parameter because animations should be executed on main thread.
=> fix: add @MainActor attribute to animation closure of custom transition

Demo/Demo/Kingfisher-Demo/Base.lproj/Main.storyboard, Demo/Demo/Kingfisher-Demo/ViewControllers/LivePhotoViewController.swift, Demo/Kingfisher-Demo.xcodeproj/project.pbxproj, Kingfisher.xcodeproj/project.pbxproj, Sources/Cache/DiskStorage.swift, Sources/Cache/ImageCache.swift, Sources/Extensions/PHLivePhotoView+Kingfisher.swift, Sources/General/ImageSource/ImageDataProvider.swift, Sources/General/ImageSource/LivePhotoSource.swift, Sources/General/Kingfisher.swift, Sources/General/KingfisherError.swift, Sources/General/KingfisherManager+LivePhoto.swift, Sources/General/KingfisherManager.swift, Sources/General/KingfisherOptionsInfo.swift, Sources/Image/ImageProcessor.swift, Sources/Networking/ImageDownloader+LivePhoto.swift, Sources/Networking/ImagePrefetcher.swift, Tests/KingfisherTests/ImageCacheTests.swift, Tests/KingfisherTests/ImageDownloaderTests.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift, Tests/KingfisherTests/KingfisherManagerTests.swift, Tests/KingfisherTests/KingfisherTestHelper.swift, Tests/KingfisherTests/LivePhotoSourceTests.swift
This PR implements the requirement of #2297 
It mainly adds a high level extension method to `PHLivePhoto` to load a live photo (with two URLs, one for still image, one for video). That means, you can now use this code to load a live photo easily:
```swift
let urls = [
URL(string: "https://example.com/image.heic")!, // imageURL
URL(string: "https://example.com/video.mov")!   // videoURL
]
let livePhotoView = PHLivePhotoView()
livePhotoView.kf.setImage(with: urls)
```
The still image and video data can be retrieved by `PHAssetResourceManager.requestData` and uploaded to the server by a user. Then in another client, these files can be loaded and it finally generates a `PHLivePhoto` object.
It is supported on all platforms where `PHLivePhotoView` is available (iOS, macOS, tvOS, etc).
For …
=> Add support for Live Photo loading from network

Sources/Networking/SessionDataTask.swift, Sources/Networking/SessionDelegate.swift
Fix a crash reported here: https://github.com/onevcat/Kingfisher/issues/2297#issuecomment-2478622132
There appears to be a brief window during which the callback can be accessed from another thread before the next lock is applied. This violates the assumption that the completion handler is invoked only once, leading to issues, particularly when task cancellation is involved.
=> Fix a potential duplicated completion invoking when task cancel

Sources/Networking/SessionDataTask.swift
=> Fix a racing on data reading in session

Sources/Image/Image.swift, Tests/KingfisherTests/ImageExtensionTests.swift
=> Fix zero image size rendering for SVG/PDF on macOS

Sources/Networking/ImageDownloader.swift
The `sessionTask` seems to be nil in some cases in our app, and so I have removed the force unwrapping.
=> 🐛 Session Task crashed with force unwrap

Sources/General/ImageSource/LivePhotoSource.swift
| | File Format | Filename extension |
|--|-|-|
| Video for Live Photos | QuickTime | mov |
| Image for Live Photos | HEIF | heic |
Kingfisher is only using the filename extensions (`heic`, `mov`) in its code, and not using `heif` or `QuickTime`/`qt` (except for the file header chunk) which is fine. However, the file type documentation contained some unclear expressions, so I improved the descriptions as follows.
> HEIC format
-> HEIF format with "heic" filename extension
> MOV format
-> QuickTime format with "mov" filename extension
=> Improve the description of the Live Photo file format

Sources/General/KingfisherManager.swift, Sources/Image/GIFAnimatedImage.swift, Sources/Image/Image.swift, Tests/KingfisherTests/KingfisherManagerTests.swift
Loading some animated image formats can be resource-intensive. To optimize performance, we should avoid reloading them from the disk cache if the loading options remain unchanged.
Fixes https://github.com/yeatse/KingfisherWebP/issues/85
=> Avoid recreating animated image representations when reloaded with identical options

Sources/Views/AnimatedImageView.swift
Use unsafely run in deinit to remove the ugly workaround.
As a UIView subclass, we should be able to assume the deinit is called in main thread.
This should fix #2351
=> Assume deinit main

Sources/Image/GIFAnimatedImage.swift, Sources/Views/AnimatedImageView.swift
Fixes #2352 
The problem is that `AnimatedImageView` currently decodes GIF images on the main thread and doesn’t adhere to `kCGImageSourceShouldCacheImmediately`. This was already a performance concern, but after #2347 was merged, the issue worsened when multiple AnimatedImageView instances shared a single CGImageSource instance.
This PR tries to fix this problem with two changes:
1. When creating `AnimatedImageView`, we now make a copy of the `CGImageSource` instance to restore the performance to pre-#2347 levels.
2. We use `UIImage.preparingForDisplay` to decode animated image frames ahead of time, eliminating the need to decode them on the main thread.
Both changes independently solve the performance issue, but both are included here for discussion and further evaluation.
=> Resolves performance issue when presenting animated images

fastlane/Fastfile
For #2359 
Contain `.xcframework` to make clear and allow Carthage to find the binary.
Now the pre-built xcframeworks files includes the `xcframework` in the file name in the release page. 
- Before: `Kingfisher-${version}.zip`
- Now: `Kingfisher-${version}.xcframework.zip` 
The `xcframework` bundle is also now direct in the zip file as its root content, instead of being nested in a folder. 
- Before: `Kingfisher-${version}.zip` -> `Kingfisher-${version}/Kingfisher.xcframework`
- Now: `Kingfisher-${version}.zip` -> `Kingfisher.xcframework`
This change is for better discoverability for some package managers. However, it might break some scripts that rely on the old structure. Please update your scripts accordingly if you were relying on the old filename and zip structure.
=> Update xcframework zip file name

Demo/Demo/Kingfisher-Demo/SwiftUIViews/MainView.swift, Demo/Demo/Kingfisher-Demo/SwiftUIViews/ProgressiveJPEGDemo.swift, Demo/Kingfisher-Demo.xcodeproj/project.pbxproj, Sources/General/KF.swift, Sources/General/KFOptionsSetter.swift, Sources/General/KingfisherManager.swift, Sources/SwiftUI/ImageBinder.swift
This allows SwiftUI uses the progressive JPEG modifier to display an image with progressive support.
Solve #1554 
https://github.com/user-attachments/assets/ca57a617-f478-4f70-92c0-3ba77adb96e1
=> Feature progressiveJPEG for SwiftUI

Sources/General/KFOptionsSetter.swift, Sources/General/KingfisherManager.swift
The progressive provider and side effect should not leak now. :]
This fixes #2299
=> Fix progressive loading provider leak

Sources/Cache/DiskStorage.swift
This tries to fix #2362 
And also try to improve the iterator perform since Swift now has a better & modern API.
=> Prevent heavy work in maybeCachedCheckingQueue

Sources/Cache/MemoryStorage.swift
DiskStorage's "config" parameter does nothing about the cleanTimer if it is set via property. I couldn't find an instance where storage is configured as such, yet the option is there and there might be users using the configuration like that.
I would usually extract a factory method to create "complex" objects like the timer here,  and making use of new Swift language features such as "[Allow implicit self for weak self captures, after self is unwrapped](https://www.hackingwithswift.com/swift/5.8/implicit-self-weak-capture)" and "[if/guard let shorthand for unwrapping optionals](https://www.hackingwithswift.com/swift/5.7/if-let-shorthand)" would be nice, but I just followed the old style to keep the code consistent.
=> Fix ineffective cleanInterval parameter in DiskStorage after initial configuration.

Kingfisher.podspec
`BUILD_LIBRARY_FOR_DISTRIBUTION = YES` is essential for both source and binary distribution, but its primary benefits and the reasons it's crucial relate to how the Swift compiler handles modules and binary compatibility. 
When enabled, the Swift compiler generates a .swiftinterface file alongside your compiled .swiftmodule. This .swiftinterface acts as a stable, textual representation of your library's public API.  It's an Application Binary Interface (ABI) contract.
This should prevent from setting the flag manually in a host app that integrates the SDK.
- CocoaPods: The line `s.pod_target_xcconfig = { 'BUILD_LIBRARY_FOR_DISTRIBUTION' => 'YES' }` in your podspec explicitly tells CocoaPods to enable this build setting when it builds your library, whether it's building it from source or …
=> feat: add BUILD_LIBRARY_FOR_DISTRIBUTION flag to podspec

Sources/Cache/DiskStorage.swift
I've refactored the cacheFileName method with the following improvements.
- Extracted the file extension setting logic into a separate method.
- Restructured the nested conditionals to clearly indicate the priority order of file extensions.
- Removed redundant forcedExtension check in the second condition from setFileExtension method since it's already been checked in the first condition. If we reach the second condition, forcedExtension is guaranteed to be nil.
I have verified that all test cases in DiskStorageTests pass after the refactoring. 
This is my first open source contribution, so please excuse any shortcomings. Thank you for your understanding.
=> Refactor cacheFileName method

Kingfisher.json
According to Cathage default behavior, Carthage would download iOS version zip to extract framework, which would cause that watchOS building may be failed. Because Kingfisher from `8.3.0` has `2 zip bundles` for resource. 
> #1992 
Add a Kingfisher.json as a workaround to let Carthage users to download the right zip by `binary "https://raw.githubusercontent.com/onevcat/Kingfisher/master/Kingfisher.json"`
=> Add Carthage support for both watchOS and iOS platforms

Tests/KingfisherTests/ImageCacheTests.swift
- Increased delay from 1 to 2 seconds in `testCleanDiskCacheWithUsedSpaceInsufficient` test
- Fixes CI test stability issues caused by disk cache file writing timing
=> Fix test timing issue in ImageCacheTests

.github/workflows/build.yaml, .github/workflows/test.yaml
- Updated GitHub Actions workflow triggers in `build.yaml` and `test.yaml`
- Prevents duplicate CI runs when creating pull requests from feature branches
- Reduces CI resource usage and wait times
- Modified workflow triggers to run only on:
- Push events to `master` branch
- Pull request events (`opened`, `synchronize`, `reopened`)
- This eliminates redundant CI runs when pushing to feature branches that also have open PRs
- 🚀 Faster feedback - no waiting for duplicate CI runs
- 💰 Reduced CI minutes usage
- 🎯 Clearer CI status - one run per change instead of two
=> Optimize CI workflow to avoid duplicate runs

Sources/Cache/DiskStorage.swift, Sources/Cache/MemoryStorage.swift, Sources/SwiftUI/ImageBinder.swift, Sources/SwiftUI/ImageContext.swift, Sources/SwiftUI/KFAnimatedImage.swift, Sources/SwiftUI/KFImageProtocol.swift, Sources/SwiftUI/KFImageRenderer.swift
- Fixed Sendable-related warnings that appear in Xcode 26 due to stricter concurrency checking
- Added appropriate Sendable constraints to generic type parameters while maintaining API compatibility
- Resolved warnings in both cache storage and SwiftUI components
- `DiskStorage.Backend`: Added `where T: Sendable` constraint
- `MemoryStorage.Backend`: Maintained existing `where T: Sendable` constraint
- Both Backend classes marked as `final` while keeping `@unchecked Sendable` for thread-safe internal state management
- Added Sendable constraints to `KFImageHoldingView` protocol and its conformances
- Updated `ImageBinder.start` method with `where HoldingView: Sendable`
- Updated `KFImage.Context` with `where HoldingView: Sendable`
- Updated `KFImageProtocol` associated type with `& …
=> Fix Sendable warnings in Xcode 26

Demo/Demo/Kingfisher-Demo/SwiftUIViews/LoadTransitionDemo.swift, Demo/Demo/Kingfisher-Demo/SwiftUIViews/MainView.swift, Demo/Kingfisher-Demo.xcodeproj/project.pbxproj, Sources/Documentation.docc/CommonTasks/CommonTasks.md, Sources/General/KingfisherOptionsInfo.swift, Sources/SwiftUI/ImageBinder.swift, Sources/SwiftUI/ImageContext.swift, Sources/SwiftUI/KFImageOptions.swift, Sources/SwiftUI/KFImageRenderer.swift
This PR adds native SwiftUI transition support to KFImage, allowing developers to use SwiftUI's built-in transition system instead of the UIKit-based ImageTransition.
- Add `loadTransition(_:animation:)` method to KFImageProtocol for setting SwiftUI transitions
- Update KFImageRenderer to properly handle SwiftUI transitions by inserting/removing views
- Refactor rendering logic to avoid unnecessary AnyView wrapping
- Update documentation to clarify that `loadTransition` is the recommended approach for SwiftUI
- Support for all SwiftUI transitions: `.slide`, `.scale`, `.opacity`, `.move`, `.offset`, etc.
- iOS 17+ support for new transitions like `.blurReplace`, `.push`
- Follows same cache behavior rules as existing fade transition
- Works with `forceTransition` option
```swift
// Basic …
```
=> Add SwiftUI native transition support for KFImage

Sources/General/KFOptionsSetter.swift, Sources/SwiftUI/KFAnimatedImage.swift, Sources/SwiftUI/KFImage.swift
- Updated documentation to accurately reflect that SwiftUI components enable `loadDiskFileSynchronously` by default
- Added clarifying notes about the different default behaviors between UIKit/AppKit and SwiftUI usage
- Explained the performance implications and how to disable this behavior if needed
This PR addresses issue #2403 which correctly pointed out that the documentation for `loadDiskFileSynchronously` was misleading. The documentation stated that disk loading happens asynchronously by default, but this is not the case for SwiftUI components (`KFImage` and `KFAnimatedImage`).
The synchronous loading default for SwiftUI is intentional and necessary to prevent image flickering during view updates in SwiftUI's declarative environment.
1. **KFOptionsSetter.swift**: Added a Note to …
=> Fix documentation for loadDiskFileSynchronously in SwiftUI components

Demo/Demo/Kingfisher-Demo/Base.lproj/Main.storyboard, Demo/Demo/Kingfisher-Demo/SwiftUIViews/MainView.swift, Demo/Demo/Kingfisher-Demo/SwiftUIViews/NetworkMetricsDemo.swift, Demo/Demo/Kingfisher-Demo/ViewControllers/NetworkMetricsViewController.swift, Demo/Demo/Kingfisher-macOS-Demo/Base.lproj/Main.storyboard, Demo/Kingfisher-Demo.xcodeproj/project.pbxproj, Kingfisher.xcodeproj/project.pbxproj, Sources/General/KingfisherManager.swift, Sources/Networking/ImageDownloader.swift, Sources/Networking/NetworkMetrics.swift, Sources/Networking/SessionDataTask.swift, Sources/Networking/SessionDelegate.swift, Tests/KingfisherTests/ImageDownloaderTests.swift
Add `NetworkMetrics` to track download performance metrics like DNS lookup time, connection time, and image retrieving time.
- Add NetworkMetrics struct to capture URLSessionTaskMetrics data
- Collect metrics in SessionDelegate through URLSession delegate method
- Pass metrics through ImageLoadingResult to RetrieveImageResult
- Metrics only available for network downloads, nil for cached results
- Support timing breakdown (DNS, TCP, TLS), data transfer, and HTTP details
- Add NetworkMetrics demo for SwiftUI and UIKit
- Track network request performance for image downloads
- View all network transactions including redirects
- Monitor download data usage and transfer sizes
- Thread-safe access from any queue
- UIKit:
```
imageView.kf.setImage(with: url) { result in
switch result {
case …
```
=> Add network metrics collection

Sources/Networking/ImageDownloader.swift
Fixed by:
- Using [weak sessionTask] capture in the closure
- Safely accessing metrics with optional chaining (sessionTask?.metrics)
=> Fix retain cycle in ImageDownloader when transferring network metrics

Kingfisher.xcodeproj/project.pbxproj, Sources/Documentation.docc/Topics/Topic_Retry.md, Sources/Networking/NetworkMonitor.swift, Sources/Networking/RetryStrategy.swift, Tests/KingfisherTests/RetryStrategyTests.swift
This PR introduces a new `NetworkRetryStrategy` that observes network connectivity and retries image downloads when network becomes available after disconnection. The implementation includes a comprehensive `NetworkMonitor` system with testability through dependency injection.
- **Network-aware retry strategy** that waits for network reconnection instead of using fixed delays
- **Immediate retry** when network is available, no artificial delays
- **Configurable timeout** for waiting for network reconnection
- **Automatic observer management** with proper cleanup
- **Protocol-oriented design** with `NetworkMonitoring` and `NetworkObserver` protocols
- **Singleton pattern** with `NetworkMonitor.default` for shared network monitoring
- **Lazy initialization** - only starts monitoring when …
=> Feature - Network retry strategy
