Kingfisher/ImageCache.swift, Kingfisher/KingfisherManager.swift, Kingfisher/UIImageView+Kingfisher.swift
Fixed some typo and added parentheses to eliminate confusion of operator precedence.
=> Fix typo and eliminate confusion.

Kingfisher-Demo/ViewController.swift, Kingfisher/ImageDownloader.swift, Kingfisher/UIImageView+Kingfisher.swift
=> Fix some typo

Kingfisher/ImageCache.swift
Fixes the world's smallest and most inconsequential typo :)
=> Fix minor typo in comment

README.md
..and thanks for open sourcing this. well done!
=> just grammatical changes

Kingfisher/ImageCache.swift, Kingfisher/ImageDownloader.swift
for multi-thread debug purpose. Add check for cache and downloader name when init.
=> Update queue name

Kingfisher.podspec, Kingfisher.xcodeproj/xcshareddata/xcbaselines/D1ED2D3E1AD2D09F00CFC3EB.xcbaseline/74237B0B-7981-4A24-B6C4-95F4A5E7727F.plist, Kingfisher.xcodeproj/xcshareddata/xcbaselines/D1ED2D3E1AD2D09F00CFC3EB.xcbaseline/Info.plist, Kingfisher/ImageCache.swift, Kingfisher/ImageDownloader.swift, KingfisherTests/ImageCacheTests.swift, KingfisherTests/ImageDownloaderTests.swift
=> [WIP] 1.1.3

Kingfisher/KingfisherManager.swift, Kingfisher/KingfisherOptionsInfo.swift, Kingfisher/UIButton+Kingfisher.swift, Kingfisher/UIImageView+Kingfisher.swift
At least it is shorter in API.
=> Update info key to enum.

Kingfisher-Demo/ViewController.swift, Kingfisher.podspec, Kingfisher.xcodeproj/project.pbxproj, Kingfisher/ImageDownloader.swift, Kingfisher/KingfisherManager.swift, Kingfisher/KingfisherOptionsInfo.swift, Kingfisher/UIButton+Kingfisher.swift, Kingfisher/UIImageView+Kingfisher.swift, KingfisherTests/ImageDownloaderTests.swift, KingfisherTests/KingfisherTestHelper.swift, KingfisherTests/UIButtonExtensionTests.swift, KingfisherTests/UIImageViewExtensionTests.swift, README.md
=> [WIP] 1.2.0

Kingfisher-Demo/ViewController.swift, Kingfisher/ImageCache.swift, Kingfisher/ImageDownloader.swift, Kingfisher/KingfisherManager.swift, Kingfisher/UIButton+Kingfisher.swift, Kingfisher/UIImageView+Kingfisher.swift, KingfisherTests/ImageDownloaderTests.swift, KingfisherTests/UIButtonExtensionTests.swift, KingfisherTests/UIImageViewExtensionTests.swift
@yadongwen 
Excellent work. I resolved the conflict and fixed tests.
Thank you!
=> Yonaskolb 1.2.1

Kingfisher/ImageCache.swift, Kingfisher/KingfisherManager.swift, KingfisherTests/ImageCacheTests.swift, KingfisherTests/ImageDownloaderTests.swift, KingfisherTests/UIButtonExtensionTests.swift, KingfisherTests/UIImageViewExtensionTests.swift, README.md
=> [WIP] 1.4.0

README.md
Big PR, I know. :stuck_out_tongue_winking_eye:
=> Fix error in Carthage installation instructions

Kingfisher/ImageCache.swift, Kingfisher/ImageDownloader.swift, Kingfisher/KingfisherManager.swift, Kingfisher/KingfisherOptions.swift, Kingfisher/UIImage+Decode.swift
I have started this PR with the intention of fixing https://github.com/onevcat/Kingfisher/issues/70, although I found a couple more things that could be improved.
I'm happy to split this PR if required.
=> Scale factor and default options

Kingfisher/KingfisherManager.swift, Kingfisher/UIImageView+Kingfisher.swift
Capture self `UIimageView` weakly inside completion block
=> Breaking retain cycles

Kingfisher-Demo/ViewController.swift, Kingfisher/UIImageView+Kingfisher.swift, KingfisherTests/UIImageViewExtensionTests.swift
This is a pull request improves #72 , which added an indicator view to the UIImage to show a progress when loading.
=> Improve #72

Kingfisher.xcodeproj/project.pbxproj, Kingfisher/ImageCache.swift, Kingfisher/UIImage+Normalize.swift
when saving to a PNG file and imageOrientation flag was lost.
This fixes #87
=> Fixes an issue where images weren't appropriately rotated

Kingfisher-Demo/ViewController.swift, Kingfisher.xcodeproj/project.pbxproj, Kingfisher/ImageTransition.swift, Kingfisher/KingfisherOptionsInfo.swift, Kingfisher/UIImageView+Kingfisher.swift
=> Transition options support

Kingfisher/Info.plist, Kingfisher/UIImageView+Kingfisher.swift
=> Fix for indicator center

Kingfisher.xcodeproj/project.pbxproj, Kingfisher/ImageCache.swift, Kingfisher/Info.plist, Kingfisher/ThreadHelper.swift, Kingfisher/UIButton+Kingfisher.swift, Kingfisher/UIImageView+Kingfisher.swift
And make memory loading on the same thread it fired
=> Prevent dispatch if already on main thread

Kingfisher/ImageCache.swift
just when data is gif, use the originalData for save
=> add support for gif

Kingfisher.podspec
Really strange stuff going on with CocoaPods. Fixes #124
=> Fixed broken Objective-C bridge

.travis.yml, Kingfisher/Info.plist, Kingfisher/KingfisherManager.swift, KingfisherTests/ImageCacheTests.swift
=> Bring cancel disk task back

Kingfisher/UIImage+Extension.swift
=> Fix JEPG format issue

README.md
🐱喵大大，文档有个小问题，看到 [这篇文章](http://swiftcafe.io/2015/11/01/kingfisher/) 引用的示例代码有问题，然后回来看，果然是直接拷贝的。optionsInfo 参数接受的数组，你少写了个 `]` ，已经帮你修改好了。
=> fix README issues

Kingfisher-Demo/ViewController.swift, Kingfisher/KingfisherManager.swift, Kingfisher/UIButton+Kingfisher.swift, Kingfisher/UIImageView+Kingfisher.swift
Fix typo of closures and getters according to https://github.com/raywenderlich/swift-style-guide
=> Fix typo of closures and getters

Kingfisher/ImageDownloader.swift, Kingfisher/KingfisherManager.swift, Kingfisher/KingfisherOptionsInfo.swift
=> Sorry for my carelessness.

Kingfisher/ImageDownloader.swift, Kingfisher/KingfisherManager.swift, KingfisherTests/ImageDownloaderTests.swift, KingfisherTests/UIImageViewExtensionTests.swift
And fixed an issue that caused all downloading cancelled when only one of the same URL downloading processes cancelled.
=> Add download task

Kingfisher-Demo/ViewController.swift
add swxftlint disable force_cast to demo
=> add swiftlint disable

.gitignore
- Ignoring `.idea` which is used by AppCode
- Clean up duplicates
=> Ignoring AppCode project folder and clean up

Sources/ImageDownloader.swift
=> Break retain cycle of ImageDownloader

Sources/ImageDownloader.swift
=> Extract auth challenge and expose it

Sources/ImageCache.swift, Sources/String+MD5.swift
1.Update the style of selector in "ImageCache.swift"
2.Update a method name in "String+MD5.swift"
=> Some changes for converting to Swift 2.2

.travis.yml
Current CI is too slow and there is no need for different device type.
=> Only for one device

Sources/ImageView+Kingfisher.swift, Sources/KingfisherManager.swift, Sources/NSButton+Kingfisher.swift, Sources/UIButton+Kingfisher.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift, Tests/KingfisherTests/NSButtonExtensionTests.swift, Tests/KingfisherTests/UIButtonExtensionTests.swift
Support optional URL for image setting APIs.
Should fix #330
=> Change image setting APIs to receive optional url

Sources/AnimatedImageView.swift, Sources/ImageCache.swift, Sources/ImageDownloader.swift, Sources/String+MD5.swift, Sources/ThreadHelper.swift, Tests/KingfisherTests/KingfisherTestHelper.swift
Remove the some compile errors and warnings.
=> Xcode 8.0 beta 2 Compatibility

Sources/AnimatedImageView.swift, Sources/Image.swift, Sources/ImageCache.swift, Sources/ImageDownloader.swift, Sources/ImagePrefetcher.swift, Sources/ImageView+Kingfisher.swift, Sources/KingfisherManager.swift, Sources/UIButton+Kingfisher.swift, Tests/KingfisherTests/ImageCacheTests.swift, Tests/KingfisherTests/ImageDownloaderTests.swift, Tests/KingfisherTests/ImagePrefetcherTests.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift, Tests/KingfisherTests/KingfisherManagerTests.swift, Tests/KingfisherTests/UIButtonExtensionTests.swift
Fix warnings for the framework and errors for test target
=> Fixes for Xcode 8b3

Sources/AnimatedImageView.swift, Sources/ImageCache.swift, Sources/ImageDownloader.swift, Sources/Resource.swift, Sources/String+MD5.swift
fix some build errors on Xcode 8 beta 4
=> compartible Xcode8 beta4

Sources/ImageDownloader.swift, Sources/KingfisherManager.swift, Sources/KingfisherOptionsInfo.swift, Tests/KingfisherTests/KingfisherManagerTests.swift, Tests/KingfisherTests/KingfisherOptionsInfoTests.swift
Could be some cases where you need to rely only in the cache and not make http requests.
I added a CacheOnly option that allows it
I hope you like it 
Any comments would be appreciated :)
Regards
=> Cache only option

Sources/ImageCache.swift
=> Use access date for expired images

.travis.yml
Fix intermittent travis build failing. See discuss in https://github.com/travis-ci/travis-ci/issues/4725
=> Sleep 5 second to let travis finish

Sources/Filter.swift, Sources/ImageCache.swift
Small fixes for Xcode 8 GM released today
=> Fix for Xcode 8 GM

Sources/AnimatedImageView.swift
Enable inheriting from AnimatedImageView
=> declare AnimateImageView as open

Sources/ImageDownloader.swift, Tests/KingfisherTests/ImageDownloaderTests.swift, Tests/KingfisherTests/UIButtonExtensionTests.swift
=> Fix multiple downloading options

Sources/Image.swift, Sources/ImageView+Kingfisher.swift, Sources/Kingfisher.swift
=> Use class for kf wrapper

Sources/Filter.swift, Sources/ImageProcessor.swift, Tests/KingfisherTests/ImageProcessorTests.swift
Fix for #485 and some trivial performance improvement too.
=> Apply filter to CIImageProcessor in data case

Sources/ImageCache.swift
Added a default disk cache path closure to ImageCache
=> Added disk cache path closure parameter to ImageCache initializer to give finer control over disk cache path

Sources/KingfisherOptionsInfo.swift
=> Expose extension and vars from KingfisherOptionsInfo extension

Sources/KingfisherManager.swift
=> Make empty task public

Sources/ImageView+Kingfisher.swift, Sources/NSButton+Kingfisher.swift, Sources/UIButton+Kingfisher.swift
=> Set placeholder image when resouce is nil

Kingfisher.xcodeproj/project.pbxproj, Sources/RequestModifier.swift
I guess `RequrstModifier.swift` should be `RequestModifier.swift`, maybe I'm wrong. 😂
=> Fix typo `RequrstModifier` -> `RequestModifier`

Sources/ImageDownloader.swift
=> Fix typo in error enum

Sources/Filter.swift, Sources/Image.swift
=> Consider image orientation when applying filter

Package.swift
=> Update Package.swift to exclude unnecessary things

Sources/Image.swift, Sources/ImageProcessor.swift, Tests/KingfisherTests/ImageDownloaderTests.swift
=> Remove scale parameter from round corner API

Sources/ImageCache.swift
=> Make Xcode 8.0 happy again

Sources/Image.swift
=> Use Float.pi instead of M_PI

Sources/NSButton+Kingfisher.swift, Sources/UIButton+Kingfisher.swift
'Modify disk and download task cancel logic' supplement for UIButton/NSButton.
=> (Supplement)Modify disk and download task cancel logic.

Sources/NSButton+Kingfisher.swift, Sources/UIButton+Kingfisher.swift
As in https://github.com/onevcat/Kingfisher/pull/598
=> Set webURLs to nil when resource is nil (NSButton and UIButton)

Sources/String+MD5.swift
=> Speed up MD5

Sources/ImageView+Kingfisher.swift, Sources/NSButton+Kingfisher.swift, Sources/UIButton+Kingfisher.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift
=> Add completion handler for web url not matched

Kingfisher.xcodeproj/project.pbxproj, Sources/Image.swift, Sources/ImageProcessor.swift, Tests/KingfisherTests/ImageProcessorTests.swift
=> Add rect corner support for round image processor

Sources/ImageCache.swift, Sources/ImageDownloader.swift, Sources/ImageView+Kingfisher.swift, Sources/KingfisherManager.swift, Sources/KingfisherOptionsInfo.swift, Sources/NSButton+Kingfisher.swift, Sources/UIButton+Kingfisher.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift, Tests/KingfisherTests/KingfisherManagerTests.swift, Tests/KingfisherTests/KingfisherOptionsInfoTests.swift
So we could set the "global" option for all methods which are using `KingfisherManager` and the extension methods.
=> Add default option property in KingfisherManager

Sources/KingfisherOptionsInfo.swift
=> Change back to collection based extension

Sources/ImageDownloader.swift, Sources/ImageView+Kingfisher.swift, Sources/Indicator.swift, Tests/KingfisherTests/ImageCacheTests.swift, Tests/KingfisherTests/ImageDownloaderTests.swift, Tests/KingfisherTests/ImagePrefetcherTests.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift, Tests/KingfisherTests/KingfisherTestHelper.swift, Tests/KingfisherTests/NSButtonExtensionTests.swift, Tests/KingfisherTests/UIButtonExtensionTests.swift
=> Cancel semaphore to solve cancel timing race

Sources/ImageDownloader.swift, Sources/ImageProcessor.swift, Sources/KingfisherManager.swift, Sources/KingfisherOptionsInfo.swift, Tests/KingfisherTests/KingfisherManagerTests.swift, Tests/KingfisherTests/KingfisherOptionsInfoTests.swift
=> Feature multi layer disk cache

Sources/AnimatedImageView.swift
=> Fix duration and FPS not match

README.md
Fix two links
before | after
--- | ---
/onevcat/Kingfisher/blob/master/blob/master/CONTRIBUTING.md | https://github.com/onevcat/Kingfisher/blob/master/CONTRIBUTING.md
/onevcat/Kingfisher/blob/master/graphs/contributors | https://github.com/onevcat/Kingfisher/graphs/contributors
=> Fix some links in README.md

Sources/ImageDownloader.swift
See https://github.com/onevcat/Kingfisher/issues/742
=> Extend AuthenticationChallengeResponsable for missing authentication schemes

Sources/ImageDownloader.swift
=> Resolve a reading racing condition

Sources/Image.swift, Sources/ImageProcessor.swift, Tests/KingfisherTests/ImageProcessorTests.swift
=> Apply scale on all image based processor methods

Sources/AnimatedImageView.swift
[Issue Link](https://github.com/onevcat/Kingfisher/issues/356)
**Todo List**
=> Play gif only once with animated image view

Demo/Kingfisher-Demo/Images.xcassets/AppIcon.appiconset/Contents.json, Kingfisher-Demo.xcodeproj/project.pbxproj, Kingfisher-Demo.xcodeproj/project.xcworkspace/contents.xcworkspacedata, Kingfisher.xcodeproj/project.pbxproj, Kingfisher.xcworkspace/contents.xcworkspacedata, fastlane/Fastfile
@frankrausch Thanks for the work.
Instead of putting the demo project outside, I added it to the workspace, so it will be easier for development purpose without switching between projects.
I would merge it and release a new version when CI passes.
=> Frankrausch master

Demo/Demo/Kingfisher-Demo/ViewController.swift, Kingfisher.xcodeproj/project.pbxproj, Sources/Box.swift, Sources/ImageView+Kingfisher.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift
=> Wrap indicator with Box for associated object

Sources/String+MD5.swift
=> Update to Swift4.1.

Sources/ImageDownloader.swift, Tests/KingfisherTests/ImageDownloaderTests.swift
=> API to cancel all downloading task

Sources/ImageDownloader.swift
This is for the work you've done in #894, just a couple of minor typos.
=> Fixed couple of typos.

Sources/Image.swift, Sources/String+MD5.swift
=> Change some functions to public type

Sources/AnimatedImageView.swift
Add equal compare with `.once` and `.finite(1)`.
=> Fix RepeatCount equal compare with .once and .finite(1)

Sources/ImageDownloader.swift
Although not ideal, this should be a quick fix for #906.
=> Serialize access to downloadHolder

Demo/Demo/Kingfisher-watchOS-Demo Extension/InterfaceController.swift, Sources/Cache/ImageCache.swift, Sources/Extensions/ImageView+Kingfisher.swift, Sources/Extensions/NSButton+Kingfisher.swift, Sources/Extensions/UIButton+Kingfisher.swift, Sources/General/KingfisherManager.swift, Sources/General/KingfisherOptionsInfo.swift, Sources/Image/Filter.swift, Sources/Image/ImageProcessor.swift, Sources/Image/ImageTransition.swift, Sources/Image/Placeholder.swift, Sources/Networking/ImageDownloader.swift, Sources/Networking/ImagePrefetcher.swift, Sources/Views/Indicator.swift, Tests/KingfisherTests/ImageCacheTests.swift, Tests/KingfisherTests/ImageDownloaderTests.swift, Tests/KingfisherTests/ImageModifierTests.swift, Tests/KingfisherTests/ImagePrefetcherTests.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift, Tests/KingfisherTests/NSButtonExtensionTests.swift, Tests/KingfisherTests/UIButtonExtensionTests.swift
@onevcat hi, We will PR on a 5.0 branch basis. #1020
=> Cleanup code 5.0

Package.swift
=> Add WKInterfaceImage+Kingfisher.swift to the Package.swift exclusion list

Kingfisher.podspec
https://github.com/onevcat/Kingfisher/issues/1035
=> Update WATCHOS_DEPLOYMENT_TARGET to 3.0

Sources/KingfisherManager.swift
=> Call completion handler for error case on waitForCache

Sources/General/KingfisherManager.swift, Tests/KingfisherTests/KingfisherManagerTests.swift
=> Fix loading cache callback option

Sources/Views/AnimatedImageView.swift
=> Consider screen scale when pre-resizing GIF frames

Kingfisher.podspec
=> Drop deployment target to 9.3 from 10.0

Sources/Cache/DiskStorage.swift
=> Mark directoryURL as public

Sources/Cache/ImageCache.swift, Tests/KingfisherTests/ImageCacheTests.swift
=> Mark wrong method as deprecated and add URL based one

Sources/Networking/SessionDelegate.swift
=> Makes lock behavior in session delegate more stable

Kingfisher.xcodeproj/project.pbxproj, Sources/Cache/CacheSerializer.swift, Sources/Image/Image.swift, Sources/Image/ImageProcessor.swift, Tests/KingfisherTests/ImageModifierTests.swift, Tests/KingfisherTests/ImageProcessorTests.swift
=> Fix downsampling with image provided

Sources/Image/Image.swift, Sources/Image/ImageDrawing.swift, Sources/Utility/String+MD5.swift, Tests/KingfisherTests/ImageExtensionTests.swift, Tests/KingfisherTests/KingfisherTestHelper.swift, Tests/KingfisherTests/MemoryStorageTests.swift
=> Fix image normalization orientation

Sources/Image/ImageProgressive.swift
=>  优化渐进处理串行队列 加强线程安全

Sources/Views/AnimatedImageView.swift
=> Wrong logic

Sources/Cache/MemoryStorage.swift
=> Remove cache delegate to prevent simultaneous op

Sources/SwiftUI/ImageBinder.swift, Sources/SwiftUI/KFImage.swift
=> Use optional source for SwiftUI

Sources/SwiftUI/ImageBinder.swift, Sources/SwiftUI/KFImage.swift
=> Fix archiving

Sources/Extensions/ImageView+Kingfisher.swift, Sources/Extensions/NSButton+Kingfisher.swift, Sources/Extensions/UIButton+Kingfisher.swift, Sources/Extensions/WKInterfaceImage+Kingfisher.swift, Sources/General/KingfisherOptionsInfo.swift, Sources/Image/ImageProgressive.swift
This should be a potential fix for #1309
=> Remove taskIdentifier callback lock and call from main

Sources/General/KingfisherManager.swift, Sources/General/KingfisherOptionsInfo.swift, Tests/KingfisherTests/KingfisherManagerTests.swift
=> Implement waiting cache for original image

Sources/Views/AnimatedImageView.swift
=> Fix wrong repeatCount calculation in AnimatedImageView

Sources/General/KingfisherManager.swift, Tests/KingfisherTests/KingfisherManagerTests.swift
=> Add init method for Xcode compiler

Sources/Cache/DiskStorage.swift, Sources/General/KingfisherError.swift
=> Throw errors when creating cache file failure

Sources/Extensions/NSButton+Kingfisher.swift
=> Add changes for Xcode 11 SPM

Sources/Image/ImageDrawing.swift
=> Remove unused variable

Sources/SwiftUI/ImageBinder.swift
This is a workaround for #1395
=> Use the normalized version of image

Sources/Networking/SessionDelegate.swift, Sources/SwiftUI/KFImage.swift
=> Replace unowned with weak references

Demo/Demo/Kingfisher-SwiftUI-Demo/Views/SwiftUIList.swift, Sources/SwiftUI/ImageBinder.swift, Sources/SwiftUI/KFImage.swift
=> Add isLoaded binding for better SwiftUI approach

fastlane/Fastfile
=> Use Xcode 11.3.1 for xcframework building

Demo/Demo/Kingfisher-Demo/ViewControllers/ProcessorCollectionViewController.swift, Sources/Image/ImageProcessor.swift
=> Add fractional round corner radius

Kingfisher.xcodeproj/project.pbxproj, Sources/General/KingfisherManager.swift, Sources/General/KingfisherOptionsInfo.swift, Sources/Networking/RetryStrategy.swift, Tests/KingfisherTests/KingfisherManagerTests.swift, Tests/KingfisherTests/KingfisherOptionsInfoTests.swift, Tests/KingfisherTests/RetryStrategyTests.swift
Add retry option to Kingfisher. For #1424
=> Feature retry

Sources/Views/AnimatedImageView.swift
=> Early return when no animator found

Sources/Extensions/ImageView+Kingfisher.swift
=> Gives a better name

Demo/Demo/Kingfisher-Demo/Base.lproj/Main.storyboard, Demo/Demo/Kingfisher-Demo/ViewControllers/TextAttachmentViewController.swift, Demo/Kingfisher-Demo.xcodeproj/project.pbxproj, Kingfisher.xcodeproj/project.pbxproj, Sources/Extensions/NSTextAttachment+Kingfisher.swift, Sources/General/Kingfisher.swift
=> Add `NSTextAttachment` support

Sources/Networking/SessionDelegate.swift
=> Give SessionDelegate an ObjC name

Sources/SwiftUI/ImageBinder.swift, Sources/SwiftUI/KFImage.swift
This should fix #1545 and #1549
=> Fix swift ui callback

Kingfisher.xcodeproj/project.pbxproj, Sources/Extensions/TVMonogramView+Kingfisher.swift, Sources/General/Kingfisher.swift
Hey, This PR adds support for `TVMonogramView` from `TVUIKit` for tvOS.
=> Adding support for TVMonogramView

Sources/Views/AnimatedImageView.swift
=> Mark some useful property/method public in Animator

Sources/General/ImageSource/ImageDataProvider.swift, Sources/General/ImageSource/Resource.swift, Sources/General/KF.swift, Sources/SwiftUI/KFImageOptions.swift
=> Optional KF init methods

Sources/Extensions/NSTextAttachment+Kingfisher.swift
These code seem added by accident through [this commit](https://github.com/onevcat/Kingfisher/commit/927f86cc0f4c184a97800ac9079f1593503f8dbf#diff-7d6701a606617e57e5ae77036b4c6b6cdbb699516a53dcd4eae083baee53af4d). Just removed these code.
=> Delete some useless code

Sources/Networking/ImageDownloader.swift, Sources/Networking/SessionDelegate.swift, Tests/KingfisherTests/ImageDownloaderTests.swift
https://github.com/onevcat/Kingfisher/issues/1619
https://github.com/onevcat/Kingfisher/pull/1620
=> 通过SessionDelegate子类实现URLSessionDataDelegate更多的协议

Demo/Demo/Kingfisher-Demo/ViewControllers/SwiftUIViewController.swift
Hi,
I removed unnecessary semicolon from SwiftUI demo.
Thanks.
=> Remove unnecessary semicolon

Sources/Views/AnimatedImageView.swift
- https://github.com/onevcat/Kingfisher/issues/1679
=> fix：AnimatedImageView Highlight gif stop play

Sources/Networking/ImageDownloader.swift, Sources/Networking/ImageDownloaderDelegate.swift, Sources/Networking/SessionDataTask.swift, Tests/KingfisherTests/ImageDownloaderTests.swift
=> Use task based on download delegate

Sources/Cache/DiskStorage.swift, Sources/Utility/String+MD5.swift, Tests/KingfisherTests/DiskStorageTests.swift
=> 为文件缓存hash之后的文件名自动添加后缀

Demo/Demo/Kingfisher-Demo/SwiftUIViews/AnimatedImageDemo.swift, Demo/Kingfisher-Demo.xcodeproj/project.pbxproj, Kingfisher.xcodeproj/project.pbxproj, Sources/General/KFOptionsSetter.swift, Sources/SwiftUI/KFAnimatedImage.swift, Sources/SwiftUI/KFAnimatedImageOptions.swift
=> Support animated images in SwiftUI

Sources/General/Kingfisher.swift
- Fix minor type in comments ( connivence -> convenience )
=> Fix minor typo

Sources/Cache/ImageCache.swift
Fixes https://github.com/onevcat/Kingfisher/issues/1533#issuecomment-831661175
=> Add correct override entry points for parsed option versions

Sources/General/ImageSource/ImageDataProvider.swift, Sources/General/KingfisherManager.swift, Tests/KingfisherTests/ImageDataProviderTests.swift
=> Confused vorlon async fetch data

Demo/Demo/Kingfisher-Demo/SwiftUIViews/SingleViewDemo.swift, Demo/Demo/Kingfisher-Demo/SwiftUIViews/TransitionViewDemo.swift, Demo/Kingfisher-Demo.xcodeproj/project.pbxproj, Sources/SwiftUI/KFAnimatedImage.swift, Sources/SwiftUI/KFImage.swift, Sources/SwiftUI/KFImageProtocol.swift, Sources/SwiftUI/KFImageRenderer.swift
=> Use ZStack for image setting now all using the same view id

Demo/Demo/Kingfisher-Demo/SwiftUIViews/AnimatedImageDemo.swift, Sources/SwiftUI/ImageContext.swift, Sources/SwiftUI/KFAnimatedImage.swift, Sources/SwiftUI/KFImage.swift, Sources/SwiftUI/KFImageProtocol.swift, Sources/SwiftUI/KFImageRenderer.swift, Sources/Views/AnimatedImageView.swift
This is for providing an option to solve #1759
=> Expose configurable animated image view

Sources/Networking/AuthenticationChallengeResponsable.swift, Sources/Networking/ImageDownloader.swift
=> Fix typo of `AuthenticationChallengeResponsable`

Sources/General/KF.swift, Sources/General/KFOptionsSetter.swift, Sources/SwiftUI/ImageBinder.swift
=> Move and apply onFailureImage to common scope

Sources/Image/ImageProcessor.swift, Tests/KingfisherTests/ImageProcessorTests.swift
=> Use color description instead of color hex for processor Id

Sources/SwiftUI/ImageBinder.swift
=> Remove explictit published

Sources/Extensions/CPListItem+Kingfisher.swift, Sources/General/KF.swift, Sources/General/Kingfisher.swift
=> Remove CarPlay support for macCatalyst platform

Sources/Networking/SessionDataTask.swift, Sources/Networking/SessionDelegate.swift, Tests/KingfisherTests/KingfisherManagerTests.swift
=> Fix an issue that callbacks are held even when the task is removed

Sources/General/KFOptionsSetter.swift
Allow configuring an AsyncImageDownloadRequestModifier via the requestModifier function of KFOptionSetter
=> Align KFOptionSetter with KingfisherParsedOptionsInfo

.spi.yml, Package.resolved, Package.swift
Add support for Swift Index DocC hosting.
=> Support build docc from SPM

Sources/Cache/ImageCache.swift, Sources/Cache/MemoryStorage.swift, Sources/Cache/Storage.swift, Sources/General/ImageSource/Source.swift, Sources/Image/ImageProcessor.swift, Sources/Image/ImageProgressive.swift, Sources/Networking/ImageDownloader.swift, Sources/Networking/SessionDelegate.swift, Sources/Utility/ExtensionHelpers.swift, Sources/Utility/Result.swift, Sources/Utility/String+MD5.swift, Tests/KingfisherTests/MemoryStorageTests.swift
This should make Kingfisher slightly smaller and slightly faster to compile.
=> Remove unused code

Demo/Demo/Kingfisher-Demo/ViewControllers/HighResolutionCollectionViewController.swift, Demo/Demo/Kingfisher-Demo/ViewControllers/InfinityCollectionViewController.swift, Sources/General/ImageSource/Resource.swift, Tests/KingfisherTests/ImageDataProviderTests.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift
=> Rename ImageResource to KF.ImageResource

Sources/PrivacyInfo.xcprivacy
Update the API use reason based on the latest documentation.
Ref: #2122
=> Update privacy file content to reflect the correct reason

Sources/Views/AnimatedImageView.swift
This covers #2152 and makes it work on other platforms too.
=> Use trait collection to determine scale

Sources/Cache/DiskStorage.swift, Tests/KingfisherTests/ImageCacheTests.swift
=> Try to recreate the cache folder after deleted manually

Sources/Cache/DiskStorage.swift, Sources/Cache/ImageCache.swift, Sources/Cache/MemoryStorage.swift, Sources/Cache/Storage.swift, Sources/General/ImageSource/AVAssetImageDataProvider.swift, Sources/General/ImageSource/ImageDataProvider.swift, Sources/General/ImageSource/Resource.swift, Sources/General/KingfisherError.swift, Sources/General/KingfisherManager.swift, Sources/Image/ImageProgressive.swift, Sources/Networking/ImageDownloader.swift, Sources/Networking/ImagePrefetcher.swift, Sources/Networking/SessionDataTask.swift, Tests/KingfisherTests/DataReceivingSideEffectTests.swift, Tests/KingfisherTests/ImageCacheTests.swift, Tests/KingfisherTests/ImageDownloaderTests.swift, Tests/KingfisherTests/ImageViewExtensionTests.swift, Tests/KingfisherTests/KingfisherManagerTests.swift, Tests/KingfisherTests/MemoryStorageTests.swift, Tests/KingfisherTests/NSButtonExtensionTests.swift, Tests/KingfisherTests/RetryStrategyTests.swift, Tests/KingfisherTests/UIButtonExtensionTests.swift
style: spelling and grammar check under the branch [v8](https://github.com/onevcat/Kingfisher/tree/v8)
> See: https://github.com/onevcat/Kingfisher/pull/2185
=> style: spelling and grammar check

Demo/Demo/Kingfisher-macOS-Demo/Base.lproj/Main.storyboard, Demo/Demo/Kingfisher-macOS-Demo/GIFHeavyViewController.swift, Demo/Demo/Kingfisher-macOS-Demo/SwiftUIViewController.swift, Demo/Kingfisher-Demo.xcodeproj/project.pbxproj, Kingfisher.xcodeproj/project.pbxproj, Sources/Image/Image.swift, Sources/Image/ImageDrawing.swift, Sources/SwiftUI/ImageContext.swift, Sources/SwiftUI/KFAnimatedImage.swift, Sources/Utility/DisplayLink.swift, Sources/Views/AnimatedImageView.swift
So that we can play animated GIFs on SwiftUI for macOS
=> Support `KFAnimatedImage` and `AnimatedImageView` on macOS

Sources/Cache/DiskStorage.swift, Sources/Cache/ImageCache.swift, Sources/General/ImageSource/ImageDataProvider.swift, Sources/General/KFOptionsSetter.swift, Sources/General/KingfisherError.swift, Sources/General/KingfisherManager.swift, Sources/Networking/ImagePrefetcher.swift, Sources/Networking/RedirectHandler.swift, Sources/Views/AnimatedImageView.swift, Tests/Dependency/Nocilla/README.md
I found some typos and fixed it
=> fix some typo 

Package@swift-5.9.swift
As discussed in https://github.com/onevcat/Kingfisher/discussions/2155#discussioncomment-9192419
=> Use process instead of copy for privacy manifest

Sources/Utility/String+MD5.swift, Tests/KingfisherTests/DiskStorageTests.swift
=> Freezy7 ext fix

Demo/Demo/Kingfisher-Demo/Base.lproj/Main.storyboard, Demo/Demo/Kingfisher-Demo/ViewControllers/PHPickerResultViewController.swift, Demo/Kingfisher-Demo.xcodeproj/project.pbxproj, Kingfisher.xcodeproj/project.pbxproj, Sources/General/ImageSource/PHPickerResultImageDataProvider.swift
=> Nuomi1 feature/ph picker result image data provider

Demo/Demo/Kingfisher-Demo/Base.lproj/Main.storyboard, Demo/Demo/Kingfisher-Demo/ViewControllers/PHPickerResultViewController.swift, Demo/Kingfisher-Demo.xcodeproj/project.pbxproj, Kingfisher.xcodeproj/project.pbxproj, Sources/General/ImageSource/PHPickerResultImageDataProvider.swift
=> feat: add PHPickerResultImageDataProvider

Sources/General/KFOptionsSetter.swift
This fixes the warning in a more correct way.
=> Remove `@unchecked` Sendable

Sources/Image/ImageDrawing.swift
This appends a compiling target fix for #2293
=> Semty blur regression fix

Demo/Demo/Kingfisher-Demo/SwiftUIViews/MainView.swift, Demo/Demo/Kingfisher-Demo/SwiftUIViews/Regression/Issue2295View.swift, Demo/Kingfisher-Demo.xcodeproj/project.pbxproj, Sources/SwiftUI/KFAnimatedImage.swift
This fixes #2295. Check the reason and discussion in the original issue.
=> Align animated image interaction behavior to normal image and iOS 17

Sources/General/ImageSource/ImageDataProvider.swift
A way to prefer using URL image source (`CGImageSourceCreateWithURL`) to generate a downsampled thumbnail. This should work quite similar with the downsampling processor, but skip & hide the explicit processing phase.
=> Provide a `ThumbnailImageDataProvider` to create thumbnail image without dealing with explicitly downloading image data

fastlane/Fastfile
Also upload the artifacts to the release page.
This fixes #1992
=> Add & Update action to create iOS-only xcframework

Demo/Demo/Kingfisher-Demo/SwiftUIViews/MainView.swift, Demo/Demo/Kingfisher-Demo/SwiftUIViews/Regression/Issue2352View.swift, Demo/Kingfisher-Demo.xcodeproj/project.pbxproj
This helps to debug the issue and prevent further regression before release.
=> Add a regression scene in demo app for #2352

Sources/SwiftUI/ImageContext.swift, Sources/SwiftUI/KFAnimatedImage.swift
=> Remove incorrect watchOS available declare

.claude/settings.local.json, .gitignore, CLAUDE.md, README-LLM.md, docs/architecture.md, docs/build-system.md, docs/deployment.md, docs/development.md, docs/files.md, docs/project-overview.md, docs/testing.md
This unlocks the potential of integrating Claude Code into the development process.
=> Add Claude guidelines

Sources/Image/ImageProcessor.swift
=> BorderImageProcessor.identifier fix
